
import SwiftData
import Foundation
/// Ein geplantes Video für einen bestimmten Tag
@Model
final class VideoSchedule {
    @Attribute(.unique) var id: UUID = UUID()
    
    var scheduledDate: Date             // Für welchen Tag
    var orderIndex: Int                 // Reihenfolge (0, 1, 2...)
    
    //  Startzeit (für Timeline-View)
    var startTime: Date?  // Wann am Tag? (z.B. 18:00)
    
    // Training Details (aus DailyExercise)
       var sets: Int?
       var reps: Int?
       
    
    // Überschreibbare Settings (von VideoMetadata defaults)
    var customRepetitions: Int?
    var customPauseSeconds: Int?
    var customLoopDurationSeconds: Int?
    
    // Status
    var isCompleted: Bool = false
    var completedAt: Date?              // ✅ MUSS DRIN SEIN!
    var rating: Int?                    // 1-5 nach Abschluss
    var notes: String?                  // Notizen nach Training
    
    
    // Wiederholungsregel
       var recurrenceRuleRaw: String = RecurrenceRule.single.rawValue
       
       var recurrenceRule: RecurrenceRule {
           get { RecurrenceRule(rawValue: recurrenceRuleRaw) ?? .single }
           set { recurrenceRuleRaw = newValue.rawValue }
       }
    // ✅ NEU: Für Wiederholungsserien - alle verknüpften Schedules
        // haben dieselbe recurrenceGroupID
        var recurrenceGroupID: UUID?
    
    var isAutoGenerated: Bool = false
    var dayOfWeek: Int = 0
    
    var isTemplate: Bool = false
    var templateUserId: UUID?
    var isWeeklyTemplate: Bool = false
    var planMode: String = "single"
    
    // Relationships
    // ✅ Relationships - CASCADE DELETE funktioniert!
    @Relationship(inverse: \Video.schedules)
       var video: Video?
       var user: User?
    
    // MARK: - Computed Properties
    
    /// Anzahl Wiederholungen (custom oder default)
    var effectiveRepetitions: Int {
        customRepetitions ?? video?.defaultRepetitions ?? 1
    }
    
    /// Pausenzeit zwischen Wiederholungen (custom oder default)
    var effectivePauseSeconds: Int {
        customPauseSeconds ?? video?.defaultPauseSeconds ?? 30
    }
    
    /// Dauer eines einzelnen Loops (custom oder default)
    var effectiveLoopDurationSeconds: Int {
        customLoopDurationSeconds ?? video?.loopDurationSeconds ?? 0
    }
    
    /// Gesamtdauer dieser Übung (Übungszeit + Pausen zwischen Wiederholungen)
    /// ⚠️ Inter-Video Pause ist NICHT enthalten - wird auf Tagesebene berechnet
    var totalDurationSeconds: Int {
        let singleDuration = effectiveLoopDurationSeconds
        let totalExerciseTime = singleDuration * effectiveRepetitions
        
        // Pausen zwischen Wiederholungen
        // Beispiel: 3 Wiederholungen → 2 Pausen (zwischen 1-2 und 2-3)
        let pauseBetweenReps = effectivePauseSeconds * max(0, effectiveRepetitions - 1)
        
        return totalExerciseTime + pauseBetweenReps
    }
    
    /// Gesamtdauer in Minuten
    var totalDurationMinutes: Int {
        totalDurationSeconds / 60
    }
    
    /// Formatierte Zeitangabe (z.B. "7:30 Min" oder "5 Min")
    var formattedDuration: String {
        let minutes = totalDurationSeconds / 60
        let seconds = totalDurationSeconds % 60
        
        if seconds > 0 {
            return "\(minutes):\(String(format: "%02d", seconds))"
        }
        return "\(minutes)"
    }
    
    // MARK: - Init
    
    init(
        scheduledDate: Date,
        startTime: Date? = nil,
        orderIndex: Int,
        video: Video,
        customRepetitions: Int? = nil,
        customPauseSeconds: Int? = nil,
        customLoopDurationSeconds: Int? = nil,
        isCompleted: Bool = false,
        completedAt: Date? = nil,
        user: User? = nil,
        sets: Int? = nil,
        reps: Int? = nil,
        recurrenceRule: RecurrenceRule = .single,
        recurrenceGroupID: UUID? = nil
     
    ) {
        self.id = UUID()
        self.scheduledDate = scheduledDate
        self.startTime = startTime ?? scheduledDate
        self.orderIndex = orderIndex
        self.video = video
        self.customRepetitions = customRepetitions
        self.customPauseSeconds = customPauseSeconds
        self.customLoopDurationSeconds = customLoopDurationSeconds
        self.isCompleted = isCompleted
        self.completedAt = completedAt
        self.user = user
        self.sets = sets
        self.reps = reps
        self.recurrenceRuleRaw = recurrenceRule.rawValue  
        self.recurrenceGroupID = recurrenceGroupID
    }
}
