/*
import SwiftData
import Foundation
/// Ein geplantes Video für einen bestimmten Tag
@Model
final class VideoSchedule {
    @Attribute(.unique) var id: UUID = UUID()

    // MARK: - Expertenmodus erkennen

    /// True, wenn dieser Schedule im Expertenmodus ist (dynamisches TempoProtocol)
    var isExpertDynamicMode: Bool {
        video?.category == .strength
        && video?.tempoProtocol?.subtype == .dynamic
    }

    // MARK: - Computed Properties (überschrieben für Expertenmodus)

    /// Anzahl Sätze (im Expertenmodus aus schedule.sets, sonst aus tempoProtocol)
    var effectiveSets: Int {
        sets ?? video?.tempoProtocol?.sets ?? 1
    }

    /// Wiederholungen pro Satz (im Expertenmodus aus schedule.reps)
    var effectiveRepsPerSet: Int {
        reps ?? video?.tempoProtocol?.reps ?? 1
    }

    /// Dauer einer einzelnen Wiederholung in Sekunden (nur sinnvoll im Expertenmodus)
    var effectiveCycleDurationSec: Int {
        video?.tempoProtocol?.cycleDurationSec ?? 0
    }

    /// Pause zwischen Sätzen (Expertenmodus) — fällt auf customPauseSeconds zurück
    var effectiveRestBetweenSetsSec: Int {
        customPauseSeconds ?? video?.tempoProtocol?.restBetweenSetsSec ?? 60
    }

    // MARK: - Anzeige

    /// Gesamtdauer in Sekunden (modusabhängig)
    var totalDurationSeconds: Int {
        if isExpertDynamicMode {
            let workPerSet = effectiveRepsPerSet * effectiveCycleDurationSec
            let totalWork = workPerSet * effectiveSets
            let totalRest = effectiveRestBetweenSetsSec * max(0, effectiveSets - 1)
            return totalWork + totalRest
        } else {
            let totalExerciseTime = effectiveLoopDurationSeconds * effectiveRepetitions
            let pauseBetweenReps = effectivePauseSeconds * max(0, effectiveRepetitions - 1)
            return totalExerciseTime + pauseBetweenReps
        }
    }

    var totalDurationMinutes: Int {
        totalDurationSeconds / 60
    }

    var formattedDuration: String {
        let minutes = totalDurationSeconds / 60
        let seconds = totalDurationSeconds % 60
        
        if seconds > 0 {
            return "\(minutes):\(String(format: "%02d", seconds))"
        }
        return "\(minutes)"
    }
    
    var weightKg: Int?
    
    var scheduledDate: Date             // Für welchen Tag
    var orderIndex: Int                 // Reihenfolge (0, 1, 2...)
    
    //  Startzeit (für Timeline-View)
    var startTime: Date?  // Wann am Tag? (z.B. 18:00)
    
    // Training Details (aus DailyExercise)
       var sets: Int?
       var reps: Int?
       
    
    // Überschreibbare Settings (von VideoMetadata defaults)
    var customRepetitions: Int?
    var customPauseSeconds: Int?
    var customLoopDurationSeconds: Int?
    
    // Status
    var isCompleted: Bool = false
    var completedAt: Date?              // ✅ MUSS DRIN SEIN!
    var rating: Int?                    // 1-5 nach Abschluss
    var notes: String?                  // Notizen nach Training
    
    
    // Wiederholungsregel
       var recurrenceRuleRaw: String = RecurrenceRule.single.rawValue
       
       var recurrenceRule: RecurrenceRule {
           get { RecurrenceRule(rawValue: recurrenceRuleRaw) ?? .single }
           set { recurrenceRuleRaw = newValue.rawValue }
       }
    // ✅ NEU: Für Wiederholungsserien - alle verknüpften Schedules
        // haben dieselbe recurrenceGroupID
        var recurrenceGroupID: UUID?
    
    var isAutoGenerated: Bool = false
    var dayOfWeek: Int = 0
    
    var isTemplate: Bool = false
    var templateUserId: UUID?
    var isWeeklyTemplate: Bool = false
    var planMode: String = "single"
    
    // Relationships
    // ✅ Relationships - CASCADE DELETE funktioniert!
    @Relationship(inverse: \Video.schedules)
       var video: Video?
       var user: User?
    
    // MARK: - Computed Properties
    
    /// Anzahl Wiederholungen (custom oder default)
    var effectiveRepetitions: Int {
        customRepetitions ?? video?.defaultRepetitions ?? 1
    }
    
    /// Pausenzeit zwischen Wiederholungen (custom oder default)
    var effectivePauseSeconds: Int {
        customPauseSeconds ?? video?.defaultPauseSeconds ?? 30
    }
    
    /// Dauer eines einzelnen Loops (custom oder default)
    var effectiveLoopDurationSeconds: Int {
        customLoopDurationSeconds ?? video?.loopDurationSeconds ?? 0
    }


    // MARK: - Init
    
    init(
        scheduledDate: Date,
        startTime: Date? = nil,
        orderIndex: Int,
        video: Video,
        customRepetitions: Int? = nil,
        customPauseSeconds: Int? = nil,
        customLoopDurationSeconds: Int? = nil,
        isCompleted: Bool = false,
        completedAt: Date? = nil,
        user: User? = nil,
        sets: Int? = nil,
        reps: Int? = nil,
        recurrenceRule: RecurrenceRule = .single,
        recurrenceGroupID: UUID? = nil
     
    ) {
        self.id = UUID()
        self.scheduledDate = scheduledDate
        self.startTime = startTime ?? scheduledDate
        self.orderIndex = orderIndex
        self.video = video
        self.customRepetitions = customRepetitions
        self.customPauseSeconds = customPauseSeconds
        self.customLoopDurationSeconds = customLoopDurationSeconds
        self.isCompleted = isCompleted
        self.completedAt = completedAt
        self.user = user
        self.sets = sets
        self.reps = reps
        self.recurrenceRuleRaw = recurrenceRule.rawValue  
        self.recurrenceGroupID = recurrenceGroupID
    }
}
*/


import SwiftData
import Foundation

/// Ein geplantes Video für einen bestimmten Tag
@Model
final class VideoSchedule {
    @Attribute(.unique) var id: UUID = UUID()
    
    var weightKg: Int?
    
    var scheduledDate: Date
    var orderIndex: Int
    var startTime: Date?
    
    // Training Details (Expert Mode)
    var sets: Int?
    var reps: Int?
    var expertPauseSeconds: Int?
    
    // Standard-Modus Settings
    var customRepetitions: Int?
    var customPauseSeconds: Int?
    var customLoopDurationSeconds: Int?
    
    // Status
    var isCompleted: Bool = false
    var completedAt: Date?
    var completedAsExpert: Bool? = nil 
    var rating: Int?
    var notes: String?
    
    // Wiederholungsregel
    var recurrenceRuleRaw: String = RecurrenceRule.single.rawValue
    
    var recurrenceRule: RecurrenceRule {
        get { RecurrenceRule(rawValue: recurrenceRuleRaw) ?? .single }
        set { recurrenceRuleRaw = newValue.rawValue }
    }
    
    var recurrenceGroupID: UUID?
    var isAutoGenerated: Bool = false
    var dayOfWeek: Int = 0
    var isTemplate: Bool = false
    var templateUserId: UUID?
    var isWeeklyTemplate: Bool = false
    var planMode: String = "single"
    
    // Relationships
    @Relationship(inverse: \Video.schedules)
    var video: Video?
    var user: User?
    
    // MARK: - Mode Detection
    
    /// True, wenn dieser Schedule prinzipiell expert-fähig ist (dynamisches TempoProtocol)
    var isExpertDynamicCapable: Bool {
        video?.category == .strength
        && video?.tempoProtocol?.subtype == .dynamic
    }
    
    // MARK: - Standard-Modus Computed
    
    /// Anzahl Wiederholungen (custom oder Fallback 3)
    var effectiveRepetitions: Int {
        customRepetitions ?? video?.defaultRepetitions ?? 3
    }
    
    /// Pausenzeit zwischen Wiederholungen (custom oder Fallback 30)
    var effectivePauseSeconds: Int {
        customPauseSeconds ?? video?.defaultPauseSeconds ?? 30
    }
    
    /// Dauer eines einzelnen Loops (custom oder Fallback 60)
    var effectiveLoopDurationSeconds: Int {
        customLoopDurationSeconds ?? video?.loopDurationSeconds ?? 60
    }
    
    // MARK: - Expert-Modus Computed
    
    /// Anzahl Sätze (custom oder aus tempoProtocol oder Fallback 3)
    var effectiveSets: Int {
        sets ?? video?.tempoProtocol?.sets ?? 3
    }
    
    /// Wiederholungen pro Satz (custom oder aus tempoProtocol oder Fallback 12)
    var effectiveRepsPerSet: Int {
        reps ?? video?.tempoProtocol?.reps ?? 12
    }
    
    /// Pause zwischen Sätzen (custom oder aus tempoProtocol oder Fallback 60)
    var effectiveExpertPauseSeconds: Int {
        expertPauseSeconds ?? video?.tempoProtocol?.restBetweenSetsSec ?? 60
    }
    
    /// Dauer einer einzelnen Wiederholung in Sekunden (aus tempoProtocol)
    var effectiveCycleDurationSec: Int {
        video?.tempoProtocol?.cycleDurationSec ?? 0
    }
    
    // MARK: - Total Duration (modus-abhängig)
    
    /// Gesamtdauer in Sekunden
    /// Expert-Modus-Berechnung wird verwendet, wenn ein TempoProtocol da ist UND
    /// Expert-Werte gesetzt sind. Sonst Standard-Berechnung.
    func totalDurationSeconds(expertModeEnabled: Bool) -> Int {
        if expertModeEnabled && isExpertDynamicCapable {
            // Expert: sets × (reps × cycleDur) + (sets-1) × restBetweenSets
            let workPerSet = effectiveRepsPerSet * effectiveCycleDurationSec
            let totalWork = workPerSet * effectiveSets
            let totalRest = effectiveExpertPauseSeconds * max(0, effectiveSets - 1)
            return totalWork + totalRest
        } else {
            // Standard: loops × loopDuration + (loops-1) × pause
            let totalExerciseTime = effectiveLoopDurationSeconds * effectiveRepetitions
            let pauseBetweenReps = effectivePauseSeconds * max(0, effectiveRepetitions - 1)
            return totalExerciseTime + pauseBetweenReps
        }
    }
    
    /// Convenience: ohne Argument — nimmt Standard-Modus
    /// (Fallback für Stellen, die noch nicht modus-aware sind)
    var totalDurationSeconds: Int {
        totalDurationSeconds(expertModeEnabled: false)
    }
    
    var totalDurationMinutes: Int {
        totalDurationSeconds / 60
    }
    
    /// Formatierte Zeitangabe (z.B. "7:30" oder "5")
    var formattedDuration: String {
        formatted(seconds: totalDurationSeconds)
    }
    
    func formattedDuration(expertModeEnabled: Bool) -> String {
        formatted(seconds: totalDurationSeconds(expertModeEnabled: expertModeEnabled))
    }
    
    private func formatted(seconds: Int) -> String {
        let minutes = seconds / 60
        let secs = seconds % 60
        if secs > 0 {
            return "\(minutes):\(String(format: "%02d", secs))"
        }
        return "\(minutes)"
    }
    
  
    /// Liefert den Modus, in dem dieser Schedule berechnet werden soll.
    /// - Wenn erledigt: damaliger Modus (eingefroren)
    /// - Wenn nicht erledigt: aktueller globaler Modus
    func effectiveExpertMode(currentExpertModeEnabled: Bool) -> Bool {
        if isCompleted {
            return completedAsExpert ?? false
        } else {
            return currentExpertModeEnabled
        }
    }

    /// Gesamtdauer in Sekunden, automatisch im richtigen Modus
    func effectiveDurationSeconds(currentExpertModeEnabled: Bool) -> Int {
        let mode = effectiveExpertMode(currentExpertModeEnabled: currentExpertModeEnabled)
        return totalDurationSeconds(expertModeEnabled: mode)
    }

    func effectiveDurationMinutes(currentExpertModeEnabled: Bool) -> Int {
        effectiveDurationSeconds(currentExpertModeEnabled: currentExpertModeEnabled) / 60
    }
    
    // MARK: - Init
    
    init(
        scheduledDate: Date,
        startTime: Date? = nil,
        orderIndex: Int,
        video: Video,
        customRepetitions: Int? = nil,
        customPauseSeconds: Int? = nil,
        customLoopDurationSeconds: Int? = nil,
        isCompleted: Bool = false,
        completedAt: Date? = nil,
        user: User? = nil,
        sets: Int? = nil,
        reps: Int? = nil,
        expertPauseSeconds: Int? = nil,        // 🆕
        recurrenceRule: RecurrenceRule = .single,
        recurrenceGroupID: UUID? = nil
    ) {
        self.id = UUID()
        self.scheduledDate = scheduledDate
        self.startTime = startTime ?? scheduledDate
        self.orderIndex = orderIndex
        self.video = video
        self.customRepetitions = customRepetitions
        self.customPauseSeconds = customPauseSeconds
        self.customLoopDurationSeconds = customLoopDurationSeconds
        self.isCompleted = isCompleted
        self.completedAt = completedAt
        self.user = user
        self.sets = sets
        self.reps = reps
        self.expertPauseSeconds = expertPauseSeconds        // 🆕
        self.recurrenceRuleRaw = recurrenceRule.rawValue
        self.recurrenceGroupID = recurrenceGroupID
    }
}
