

import SwiftData
import Foundation

/// Ein geplantes Video für einen bestimmten Tag
@Model
final class VideoSchedule {
    @Attribute(.unique) var id: UUID = UUID()
    
    
    // MARK: - Mobility-Konstanten
/// ⚠️ Wird das Mobility-Tempo im Code geändert, muss dieser Wert angepasst werden.
    static let mobilityCycleSeconds: Int = 6
    
    
    
    
    
    var weightKg: Int?
    
    var scheduledDate: Date
    var orderIndex: Int
    var startTime: Date?
    
        // Training Details (Expert Mode)
        var sets: Int?
        var reps: Int?
        var expertPauseSeconds: Int?

    // Training Details (Mobility Mode)
       
        var mobilitySets: Int?
        var mobilityReps: Int?
        var mobilityPauseSeconds: Int?
        var mobilityWeightKg: Int?
    
    //mobility Mode
    var mobilityFeedback: Double?

    // Progress-Feedback (History/Statistik), normalisiert auf 0.0-1.0.
    // Slider direkt, Smileys (0-5) als value/5.0.
    var progressFeedback: Double?
    
    // Standard-Modus Settings
    var customRepetitions: Int?
    var customPauseSeconds: Int?
    var customLoopDurationSeconds: Int?
    
    // Status
    var isCompleted: Bool = false
        var completedAt: Date?
        var completedAsExpert: Bool? = nil
        /// Eingefrorener Modus zum Zeitpunkt des Abschließens (WorkoutModus.rawValue).
        var completedModusRaw: String? = nil
        var rating: Int?
    var notes: String?
    
    // Wiederholungsregel
    var recurrenceRuleRaw: String = RecurrenceRule.single.rawValue
    
    var recurrenceRule: RecurrenceRule {
        get { RecurrenceRule(rawValue: recurrenceRuleRaw) ?? .single }
        set { recurrenceRuleRaw = newValue.rawValue }
    }
    
    var recurrenceGroupID: UUID?
    var isAutoGenerated: Bool = false
    var dayOfWeek: Int = 0
    var isTemplate: Bool = false
    var templateUserId: UUID?
    var isWeeklyTemplate: Bool = false
    var planMode: String = "single"
    
    // Relationships
    @Relationship(inverse: \Video.schedules)
    var video: Video?
    var user: User?
    
    // MARK: - Mode Detection
    
    /// True, wenn dieser Schedule prinzipiell expert-fähig ist (dynamisches TempoProtocol)
    var isExpertDynamicCapable: Bool {
        video?.category == .strength
        && video?.tempoProtocol?.subtype == .dynamic
    }
    
    // MARK: - Standard-Modus Computed
    
    /// Anzahl Wiederholungen (custom oder Fallback 3)
    var effectiveRepetitions: Int {
        customRepetitions ?? video?.defaultRepetitions ?? PlaybackDefaults.repetitions
    }
    
    /// Pausenzeit zwischen Wiederholungen (custom oder Fallback 30)
    var effectivePauseSeconds: Int {
        customPauseSeconds ?? video?.defaultPauseSeconds ?? PlaybackDefaults.pauseSeconds
    }
    
    /// Dauer eines einzelnen Loops (custom oder Fallback 60)
    var effectiveLoopDurationSeconds: Int {
        customLoopDurationSeconds ?? video?.loopDurationSeconds ?? PlaybackDefaults.loopDurationSeconds
    }
    
    // MARK: - Expert-Modus Computed
    
    /// Anzahl Sätze (custom oder aus tempoProtocol oder Fallback 3)
    var effectiveSets: Int {
        sets ?? video?.tempoProtocol?.sets ?? 3
    }
    
    /// Wiederholungen pro Satz (custom oder aus tempoProtocol oder Fallback 12)
    var effectiveRepsPerSet: Int {
        reps ?? video?.tempoProtocol?.reps ?? 12
    }
    
    /// Pause zwischen Sätzen (custom oder aus tempoProtocol oder Fallback 60)
    var effectiveExpertPauseSeconds: Int {
        expertPauseSeconds ?? video?.tempoProtocol?.restBetweenSetsSec ?? 60
    }
    
    /// Dauer einer einzelnen Wiederholung in Sekunden (aus tempoProtocol)
        var effectiveCycleDurationSec: Int {
            video?.tempoProtocol?.cycleDurationSec ?? 0
        }
        
        // MARK: - Modus-aware Pill-Werte
        
        /// Sätze passend zum Modus.
        /// Mobility liest mobilitySets, sonst sets — jeweils mit den
        /// vorhandenen Fallbacks.
        func activeSets(modus: WorkoutModus) -> Int {
            modus == .mobility
                ? (mobilitySets ?? video?.tempoProtocol?.sets ?? 3)
                : effectiveSets
        }
        
        /// Wiederholungen pro Satz passend zum Modus.
        func activeReps(modus: WorkoutModus) -> Int {
            modus == .mobility
                ? (mobilityReps ?? video?.tempoProtocol?.reps ?? 20)
                : effectiveRepsPerSet
        }
        
        /// Satzpause passend zum Modus.
        func activePauseSeconds(modus: WorkoutModus) -> Int {
            modus == .mobility
                ? (mobilityPauseSeconds ?? video?.tempoProtocol?.restBetweenSetsSec ?? 60)
                : effectiveExpertPauseSeconds
        }
        
        /// Gewicht passend zum Modus. Optional — nil heißt
        /// "kein Gewicht gesetzt" (Player fragt dann nach).
        func activeWeightKg(modus: WorkoutModus) -> Int? {
            modus == .mobility ? mobilityWeightKg : weightKg
        }
        

    
    // MARK: - Total Duration (modus-abhängig)
    
    /// Gesamtdauer in Sekunden
    /// Expert-Modus-Berechnung wird verwendet, wenn ein TempoProtocol da ist UND
    /// Expert-Werte gesetzt sind. Sonst Standard-Berechnung.
    func totalDurationSeconds(modus: WorkoutModus) -> Int {
            let usesPill = (modus == .expert || modus == .mobility) && isExpertDynamicCapable

            if usesPill {
                // Pille: sets × (reps × cycleDur) + (sets-1) × pause
                // Mobility nutzt das feste 3-0-3-Tempo, Expert das Video-Tempo.
                let cycle = (modus == .mobility)
                    ? VideoSchedule.mobilityCycleSeconds
                    : effectiveCycleDurationSec
                let sets = activeSets(modus: modus)
                let reps = activeReps(modus: modus)
                let pause = activePauseSeconds(modus: modus)

                let totalWork = sets * reps * cycle
                let totalRest = pause * max(0, sets - 1)
                return totalWork + totalRest
            } else {
                // Standard: loops × loopDuration + (loops-1) × pause
                let totalExerciseTime = effectiveLoopDurationSeconds * effectiveRepetitions
                let pauseBetweenReps = effectivePauseSeconds * max(0, effectiveRepetitions - 1)
                return totalExerciseTime + pauseBetweenReps
            }
        }
    
    /// Convenience: ohne Argument — nimmt Standard-Modus
    /// (Fallback für Stellen, die noch nicht modus-aware sind)
    /// Convenience: ohne Argument — nimmt Standard-Modus
        /// (Fallback für Stellen, die noch nicht modus-aware sind)
        var totalDurationSeconds: Int {
            totalDurationSeconds(modus: .standard)
        }
    
    var totalDurationMinutes: Int {
        totalDurationSeconds / 60
    }
    
    /// Formatierte Zeitangabe (z.B. "7:30" oder "5")
    var formattedDuration: String {
        formatted(seconds: totalDurationSeconds)
    }
    
    func formattedDuration(modus: WorkoutModus) -> String {
            formatted(seconds: totalDurationSeconds(modus: modus))
        }
    
    private func formatted(seconds: Int) -> String {
        let minutes = seconds / 60
        let secs = seconds % 60
        if secs > 0 {
            return "\(minutes):\(String(format: "%02d", secs))"
        }
        return "\(minutes)"
    }
    
  
    /// Liefert den Modus, in dem dieser Schedule berechnet werden soll.
    /// - Wenn erledigt: damaliger Modus (eingefroren)
    /// - Wenn nicht erledigt: aktueller globaler Modus
    /// Liefert den Modus, in dem dieser Schedule berechnet werden soll.
        /// - Wenn erledigt: eingefrorener Modus von damals
        /// - Wenn nicht erledigt: aktueller globaler Modus
        func effectiveModus(current: WorkoutModus) -> WorkoutModus {
            if isCompleted {
                return completedModusRaw.flatMap(WorkoutModus.init(rawValue:)) ?? current
            } else {
                return current
            }
        }

    /// Gesamtdauer in Sekunden, automatisch im richtigen Modus.
            /// Abgeschlossene Schedules nutzen ihren eingefrorenen Modus.
            func effectiveDurationSeconds(modus: WorkoutModus) -> Int {
                totalDurationSeconds(modus: effectiveModus(current: modus))
            }

        func effectiveDurationMinutes(modus: WorkoutModus) -> Int {
            effectiveDurationSeconds(modus: modus) / 60
        }
    
    
    
    
    
    // MARK: - Init
    
    init(
        scheduledDate: Date,
        startTime: Date? = nil,
        orderIndex: Int,
        video: Video,
        customRepetitions: Int? = nil,
        customPauseSeconds: Int? = nil,
        customLoopDurationSeconds: Int? = nil,
        isCompleted: Bool = false,
        completedAt: Date? = nil,
        user: User? = nil,
        sets: Int? = nil,
        reps: Int? = nil,
        expertPauseSeconds: Int? = nil,
        mobilitySets: Int? = nil,
               mobilityReps: Int? = nil,
               mobilityPauseSeconds: Int? = nil,
        mobilityWeightKg: Int? = nil,
        recurrenceRule: RecurrenceRule = .single,
        recurrenceGroupID: UUID? = nil
    ) {
        self.id = UUID()
        self.scheduledDate = scheduledDate
        self.startTime = startTime ?? scheduledDate
        self.orderIndex = orderIndex
        self.video = video
        self.customRepetitions = customRepetitions
        self.customPauseSeconds = customPauseSeconds
        self.customLoopDurationSeconds = customLoopDurationSeconds
        self.isCompleted = isCompleted
        self.completedAt = completedAt
        self.user = user
        self.sets = sets
        self.reps = reps
        self.expertPauseSeconds = expertPauseSeconds
        self.mobilitySets = mobilitySets
                self.mobilityReps = mobilityReps
                self.mobilityPauseSeconds = mobilityPauseSeconds
        self.mobilityWeightKg = mobilityWeightKg
        self.recurrenceRuleRaw = recurrenceRule.rawValue
        self.recurrenceGroupID = recurrenceGroupID
    }
}
