

import SwiftUI
import SwiftData

struct CalendarView: View {
    @EnvironmentObject var profileVM: ProfileViewModel
    @EnvironmentObject var authService: AuthService
    @EnvironmentObject var progressVM: ProgressViewModel
    
    @EnvironmentObject var appointmentViewModel: AppointmentViewModel
    @EnvironmentObject var calendarViewModel: CalendarViewModel
    @EnvironmentObject var videoLibraryVM: VideoLibraryViewModel
    @EnvironmentObject private var settingsVM: SettingsViewModel
    
    // ✅ @Query für Termine
    @Query private var allAppointments: [Appointment]
       
    // ✅ Gefilterte Termine (nur 24h Cutoff, User-Filter schon in Query!)
      private var appointments: [Appointment] {
          allAppointments.filter { $0.date > Date().addingTimeInterval(-86400) }
      }
 
    @State private var videoPlayerItem: VideoPlayerItem?
    
    @State private var pendingVideo: Video?
    @State private var pendingDate: Date = Date()
    @State private var showScopeDialog = false
    @State private var pendingRecurrenceRule: RecurrenceRule = .single
    @State private var pendingDeleteSchedule: VideoSchedule?
    @State private var showDeleteScopeDialog = false

    
    @State private var showFilterSheet = false
    @State private var selectedVideo: Video?
    @State private var pickerPresented = false
    
    
    @Environment(\.modelContext) var modelContext
    @State private var currentWeekOffset = 0
    
  

  
    @State private var editingScheduleId: UUID?  // ← Für EDIT!
    @State private var isEditingMode = false
    @State private var activeSheet: SheetType?
    @State private var selectedVideoForConfig: Video?
    @State private var playbackSettings = PlaybackSettings()

    
    var onVideoSelected: ((Video) -> Void)? = nil
    
        private var currentUser: User? {
            authService.currentUser
        }
        
        // ✅ Gefilterte Termine (MIT User-Check!)
        private var userAppointments: [Appointment] {
            guard let userId = currentUser?.id else {
                return []
            }
            return allAppointments.filter {
                $0.userId == userId &&
                $0.date > Date().addingTimeInterval(-86400) &&
                $0.status != .cancelled  
            }
        }
    
    // Diese privaten Funktionen in CalendarView ergänzen:

    private func handleDelete(_ schedule: VideoSchedule) {
        let rule = settingsVM.preferences
            .getGoalFor(dayOfWeek: schedule.dayOfWeek)?.recurrenceRule ?? .single
        
        if rule == .single || !schedule.isAutoGenerated {
            progressVM.removeSchedule(schedule, for: authService.currentUser!)
        } else {
            pendingDeleteSchedule = schedule
            showDeleteScopeDialog = true
        }
    }

    private func handleConfig(_ schedule: VideoSchedule) {
        editingScheduleId = schedule.id
        selectedVideoForConfig = schedule.video
        playbackSettings = PlaybackSettings(
            repetitions: schedule.customRepetitions ?? 3,
            pauseSeconds: schedule.customPauseSeconds ?? 30,
            loopDurationSeconds: schedule.customLoopDurationSeconds
                ?? schedule.video?.loopDurationSeconds
                ?? 120
        )
    }

    private func handlePlay(_ schedule: VideoSchedule, _ video: Video) {
        videoPlayerItem = VideoPlayerItem(video: video, scheduleId: schedule.id)
    }
    
    
    enum SheetType: Identifiable {
        case
        library,
        profile,
        appointments,
        settings
        var id: Self { self }
    }
    
    
    
    var body: some View {

                VStack(spacing: 0) {
                    CompactWeekView()

                    ScrollView {
                        VStack(spacing: 16) {
                            SelectedDateInfoView(
                                selectedDate: calendarViewModel.selectedDate,
                                appointments: userAppointments.filter { Calendar.current.isDate($0.date, inSameDayAs: calendarViewModel.selectedDate) },
                                onAddAppointment: {
                                    activeSheet = .appointments
                                    print("Add Appointment tapped") })
                       
                            .padding(.horizontal, 16)
                            .padding(.top, 12)
                            
                            
                            ExercisesForDateView(
                                selectedDate: calendarViewModel.selectedDate,
                                onAddExercise: {
                                    activeSheet = .library
                                },
                                onConfig: { schedule in
                                    handleConfig(schedule)
                                },
                                onPlay: { schedule, video in
                                    handlePlay(schedule, video)
                                },
                                onDelete: { schedule in
                                    handleDelete(schedule)
                                }
                           
                            )


                            
                        }
                        .padding(.bottom, 20)
                    }
                
                .background(Color(.systemGroupedBackground))
                .navigationTitle("Kalender")
                .toolbar {
                    toolbarContent
                }
                .navigationBarTitleDisplayMode(.inline)
               
  
                   .onChange(of: calendarViewModel.selectedDate) { _, newDate in
                       if let user = authService.currentUser {
                           progressVM.loadToday(for: user, date: newDate)  // ← NICHT calculateProgress!
                       }
                    }
                
                   .sheet(item: $activeSheet) { sheet in
                       switch sheet {
                       case .settings:
                           SettingsView() // ← user Parameter
                               .environmentObject(settingsVM)   // ← VM injizieren!
                               .environment(\.modelContext, settingsVM.modelContext)
                               .onDisappear {
                                   progressVM.loadToday(for: authService.currentUser!)
                               }
                       case .library:
                           NavigationStack {
                               LibraryView(
                                onVideoSelected: { video in
                                    activeSheet = nil
                                    
                                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                                        pendingDate = calendarViewModel.selectedDate
                                        editingScheduleId = nil
                                        playbackSettings = PlaybackSettings(
                                            repetitions: video.defaultRepetitions,
                                            pauseSeconds: video.defaultPauseSeconds,
                                            loopDurationSeconds: video.loopDurationSeconds
                                        )
                                        selectedVideoForConfig = video
                                    }
                                }
                               )
                          
                           }
                       case .profile:
                           ProfileView()
                               
                       case .appointments:
                           ManualAppointmentEntryView()  
                                   
                       }
                   }

                   .sheet(item: $selectedVideoForConfig) { video in
                       VideoQuickConfigSheet(
                           video: video,
                           initialRepetitions: playbackSettings.repetitions,
                           initialLoopDuration: playbackSettings.loopDurationSeconds,
                           initialPause: playbackSettings.pauseSeconds,
                           onAdd: { reps, loopDuration, pause in
                               if let scheduleId = editingScheduleId,
                                  let schedule = progressVM.todaysSchedules.first(where: { $0.id == scheduleId }) {
                                   schedule.customRepetitions = reps
                                   schedule.customPauseSeconds = pause
                                   schedule.customLoopDurationSeconds = loopDuration
                                   progressVM.updateSchedule(schedule, for: authService.currentUser!)
                               } else {
                                   // ✅ Neues Video hinzufügen
                                   let rule = settingsVM.recurrenceRule(for: pendingDate)
                                   if rule == .single {
                                       progressVM.addVideo(
                                           video,
                                           to: pendingDate,
                                           for: authService.currentUser!,
                                           customRepetitions: reps,
                                           customPauseSeconds: pause,
                                           customLoopDuration: loopDuration
                                       )
                                   } else {
                                       pendingVideo = video
                                       pendingRecurrenceRule = rule
                                       showScopeDialog = true
                                   }
                               }
                               selectedVideoForConfig = nil
                               editingScheduleId = nil
                           },
                           onCancel: {
                               selectedVideoForConfig = nil
                               editingScheduleId = nil
                           }
                       )
                   }
                   .sheet(item: $videoPlayerItem) { item in
                       VideoPlayerView(
                           video: item.video,
                           scheduleId: item.scheduleId,
                           progressViewModel: progressVM
                       )
                   }
    
                .confirmationDialog(
                    "Video einplanen",
                    isPresented: $showScopeDialog,
                    titleVisibility: .visible
                ) {
                    Button("Nur für diesen Tag") {
                        if let video = pendingVideo {
                            settingsVM.addVideoWithScope(
                                video,
                                to: pendingDate,
                                for: authService.currentUser!,
                                scope: .onlyToday,
                                progressVM: progressVM
                            )
                        }
                        pendingVideo = nil
                    }
                    Button("Für alle \(pendingRecurrenceRule.rawValue) Termine") {
                        if let video = pendingVideo {
                            settingsVM.addVideoWithScope(
                                video,
                                to: pendingDate,
                                for: authService.currentUser!,
                                scope: .allFuture,
                                progressVM: progressVM
                            )
                        }
                        pendingVideo = nil
                    }
                    Button("Abbrechen", role: .cancel) { pendingVideo = nil }
                } message: {
                    Text("Soll \"\(pendingVideo?.title ?? "")\" nur heute oder für alle \(pendingRecurrenceRule.rawValue.lowercased()) Termine eingeplant werden?")
                }
                .confirmationDialog(
                    "Video entfernen",
                    isPresented: $showDeleteScopeDialog,
                    titleVisibility: .visible
                ) {
                    Button("Nur diesen Tag", role: .destructive) {
                        if let schedule = pendingDeleteSchedule {
                            settingsVM.removeScheduleWithScope(
                                schedule,
                                for: authService.currentUser!,
                                scope: .onlyToday,
                                progressVM: progressVM
                            )
                        }
                        pendingDeleteSchedule = nil
                    }
                    Button("Alle zukünftigen Termine", role: .destructive) {
                        if let schedule = pendingDeleteSchedule {
                            settingsVM.removeScheduleWithScope(
                                schedule,
                                for: authService.currentUser!,
                                scope: .allFuture,
                                progressVM: progressVM
                            )
                        }
                        pendingDeleteSchedule = nil
                    }
                    Button("Abbrechen", role: .cancel) { pendingDeleteSchedule = nil }
                } message: {
                    Text("Soll \"\(pendingDeleteSchedule?.video?.title ?? "")\" nur heute oder für alle zukünftigen Termine entfernt werden?")
                }

                   .onAppear {
                               guard let user = currentUser else {
                                   print("⚠️ HomeView: Kein User eingeloggt")
                                   return
                               }
                               print("🏠 HomeView onAppear - currentUser.email: '\(user.email)'")
                               progressVM.loadToday(for: user)
                           }
        }
    }
    
    
    @ToolbarContentBuilder
    var toolbarContent: some ToolbarContent {
        // LINKS: Plus + Filter
        ToolbarItem(placement: .topBarLeading) {
            HStack(spacing: 12) {
                
            }
        }
        
        // RECHTS: Profile-Menü
        ToolbarItem(placement: .topBarTrailing) {
            Menu {
                Button("Profil") {
                    activeSheet = .profile                 }
                Button("Einstellungen") {
                    activeSheet = .settings
                }
            } label: {
                // ✅ PROFILBILD STATT ICON
                           if let user = authService.currentUser,
                              let imageData = user.profileImage,
                              let uiImage = UIImage(data: imageData) {
                               Image(uiImage: uiImage)
                                   .resizable()
                                   .scaledToFill()
                                   .frame(width: 35, height: 35)
                                   .clipShape(Circle())
                           } else {
                               Circle()
                                   .fill(Color.accentColor.opacity(0.3))
                                   .frame(width: 35, height: 35)
                                   .overlay(
                                       Text(authService.currentUser?.initials ?? "?")
                                           .font(.system(size: 14, weight: .bold))
                                           .foregroundStyle(Color.accentColor)
                                   )
                           }
            }
        }
    }
}
#Preview("CalendarView") {
    let config = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(
        for: VideoSchedule.self, Appointment.self,
        configurations: config
    )
    
    CalendarView()
        .modelContainer(container)
}
