

import SwiftUI
import SwiftData

struct CalendarView: View {
    @EnvironmentObject var profileVM: ProfileViewModel
    @EnvironmentObject var authService: AuthService
    @EnvironmentObject var progressVM: ProgressViewModel
    
    @EnvironmentObject var appointmentViewModel: AppointmentViewModel
    @EnvironmentObject var calendarViewModel: CalendarViewModel
    @EnvironmentObject var videoLibraryVM: VideoLibraryViewModel
    @EnvironmentObject private var settingsVM: SettingsViewModel
    
    // ✅ @Query für Termine
    @Query private var allAppointments: [Appointment]
       
    // ✅ Gefilterte Termine (nur 24h Cutoff, User-Filter schon in Query!)
      private var appointments: [Appointment] {
          allAppointments.filter { $0.date > Date().addingTimeInterval(-86400) }
      }
    
    @State private var pendingVideo: Video?
    @State private var pendingDate: Date = Date()
    @State private var showScopeDialog = false
    @State private var pendingRecurrenceRule: RecurrenceRule = .single
    @State private var pendingDeleteSchedule: VideoSchedule?
    @State private var showDeleteScopeDialog = false

    
    @State private var showFilterSheet = false
    @State private var selectedVideo: Video?
    @State private var pickerPresented = false
    
    
    @Environment(\.modelContext) var modelContext
    @State private var currentWeekOffset = 0
    
    @State private var selectedScheduleId: UUID?  // ← NEU!
    @State private var showVideoPlayer = false  // ← NEU!
    @State private var selectedVideoForPlayer: Video?  // ← NEU!
    @State private var editingScheduleId: UUID?  // ← Für EDIT!
    @State private var isEditingMode = false
    @State private var activeSheet: SheetType?
    @State private var selectedVideoForConfig: Video?
    @State private var playbackSettings = PlaybackSettings()

    
    var onVideoSelected: ((Video) -> Void)? = nil
    
    init(repository: VideoRepositoryProtocol,
         onVideoSelected: ((Video) -> Void)? = nil) {
        self.onVideoSelected = onVideoSelected
        // ✅ Variante 1: Query OHNE Filter, Filter in computed property
            _allAppointments = Query(sort: \Appointment.date)
        }
        
        private var currentUser: User? {
            authService.currentUser
        }
        
        // ✅ Gefilterte Termine (MIT User-Check!)
        private var userAppointments: [Appointment] {
            guard let userId = currentUser?.id else {
                return []
            }
            return allAppointments.filter {
                $0.userId == userId &&
                $0.date > Date().addingTimeInterval(-86400)
            }
        }
    
    // Diese privaten Funktionen in CalendarView ergänzen:

    private func handleDelete(_ schedule: VideoSchedule) {
        let rule = settingsVM.preferences
            .getGoalFor(dayOfWeek: schedule.dayOfWeek)?.recurrenceRule ?? .single
        
        if rule == .single || !schedule.isAutoGenerated {
            progressVM.removeSchedule(schedule, for: authService.currentUser!)
        } else {
            pendingDeleteSchedule = schedule
            showDeleteScopeDialog = true
        }
    }

    private func handleConfig(_ schedule: VideoSchedule) {
        editingScheduleId = schedule.id
        selectedVideoForConfig = schedule.video
        playbackSettings = PlaybackSettings(
            repetitions: schedule.customRepetitions ?? 3,
            pauseSeconds: schedule.customPauseSeconds ?? 30,
            loopDurationSeconds: schedule.customLoopDurationSeconds
                ?? schedule.video?.loopDurationSeconds
                ?? 120
        )
    }

    private func handlePlay(_ schedule: VideoSchedule, _ video: Video) {
        selectedScheduleId = schedule.id
        selectedVideoForPlayer = video
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                showVideoPlayer = true
            }
    }
    enum SheetType: Identifiable {
        case
        library,
        profile,
        appointments,
        settings
        var id: Self { self }
    }
    
    
    
    var body: some View {

            ZStack {
                Color(.systemGroupedBackground).ignoresSafeArea()
                
                
                VStack {
                    CompactWeekView()
                    
                    Divider()
                        .padding(.vertical,8)
                    
                    ScrollView {
                        VStack(spacing: 20) {
                            SelectedDateInfoView(
                                selectedDate: calendarViewModel.selectedDate,
                                appointments: userAppointments.filter { Calendar.current.isDate($0.date, inSameDayAs: calendarViewModel.selectedDate) },
                                onAddAppointment: {
                                    activeSheet = .appointments
                                    print("Add Appointment tapped") })
                            //TODO: Funktion für onAddExercise
                            .padding(.horizontal, 16)
                            
                            ExercisesForDateView(
                                selectedDate: calendarViewModel.selectedDate,
                                onAddExercise: {
                                    activeSheet = .library
                                },
                                onConfig: { schedule in
                                    handleConfig(schedule)
                                },
                                onPlay: { schedule, video in
                                    handlePlay(schedule, video)
                                },
                                onDelete: { schedule in
                                    handleDelete(schedule)
                                },
                           
                            )


                            
                        }
                  //      .padding()
                    }
                }
                .navigationTitle("Kalender")
                .toolbar {
                    toolbarContent
                }
                .navigationBarTitleDisplayMode(.inline)
               
  
                   .onChange(of: calendarViewModel.selectedDate) { _, newDate in
                       if let user = authService.currentUser {
                           progressVM.loadToday(for: user, date: newDate)  // ← NICHT calculateProgress!
                       }
                    }
                
                   .sheet(item: $activeSheet) { sheet in
                       switch sheet {
                       case .settings:
                           SettingsView() // ← user Parameter
                               .environmentObject(settingsVM)   // ← VM injizieren!
                               .environment(\.modelContext, settingsVM.modelContext)
                               .onDisappear {
                                   progressVM.loadToday(for: authService.currentUser!)
                               }
                       case .library:
                           NavigationStack {
                               LibraryView(
                                   onVideoSelected: { video in
                                       let date = calendarViewModel.selectedDate
                                       let dayOfWeek = (Calendar.current.component(
                                           .weekday, from: date) + 5) % 7
                                       let rule = settingsVM.preferences
                                           .getGoalFor(dayOfWeek: dayOfWeek)?.recurrenceRule ?? .single
                                       activeSheet = nil
                                       
                                       DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                                           if rule == .single {
                                               progressVM.addVideo(
                                                   video,
                                                   to: date,
                                                   for: authService.currentUser!
                                               )
                                           } else {
                                               pendingVideo = video
                                               pendingDate = date
                                               pendingRecurrenceRule = rule
                                               showScopeDialog = true
                                           }
                                       }
                                       selectedVideoForConfig = video 
                                   }
                               )
                               .environmentObject(authService)
                               .environmentObject(videoLibraryVM)
                               .environmentObject(settingsVM)
                           }
                       case .profile:
                           ProfileView()
                               .environmentObject(authService)
                               .environment(\.modelContext, profileVM.modelContext)

                               
                           
                           
                       case .appointments:
                           ManualAppointmentEntryView(viewModel: appointmentViewModel)  // ← HIER!
                                     .environmentObject(authService)
                                     .environmentObject(appointmentViewModel)
                       }
                   }

                   .sheet(item: $selectedVideoForConfig) { video in
                       VideoQuickConfigSheet(
                           video: video,
                           initialRepetitions: playbackSettings.repetitions,
                           initialLoopDuration: playbackSettings.loopDurationSeconds,
                           initialPause: playbackSettings.pauseSeconds,
                           onAdd: { reps, loopDuration, pause in
                               if let scheduleId = editingScheduleId,
                                  let schedule = progressVM.todaysSchedules.first(where: { $0.id == scheduleId }) {
                                   schedule.customRepetitions = reps
                                   schedule.customPauseSeconds = pause
                                   schedule.customLoopDurationSeconds = loopDuration
                                   progressVM.updateSchedule(schedule, for: authService.currentUser!)
                               }
                               selectedVideoForConfig = nil
                               editingScheduleId = nil
                           },
                           onCancel: {
                               selectedVideoForConfig = nil
                               editingScheduleId = nil
                           }
                       )
                   }
                   .sheet(isPresented: $showVideoPlayer) {
                       if let video = selectedVideoForPlayer,
                          let scheduleId = selectedScheduleId {
                           VideoPlayerView(
                               video: video,
                               scheduleId: scheduleId,  // ✅ DEINE STATE VARIABLE!
                               progressViewModel: progressVM
                           )
                       }
                   }
    
                .confirmationDialog(
                    "Video einplanen",
                    isPresented: $showScopeDialog,
                    titleVisibility: .visible
                ) {
                    Button("Nur für diesen Tag") {
                        if let video = pendingVideo {
                            settingsVM.addVideoWithScope(
                                video,
                                to: pendingDate,
                                for: authService.currentUser!,
                                scope: .onlyToday,
                                progressVM: progressVM
                            )
                        }
                        pendingVideo = nil
                    }
                    Button("Für alle \(pendingRecurrenceRule.rawValue) Termine") {
                        if let video = pendingVideo {
                            settingsVM.addVideoWithScope(
                                video,
                                to: pendingDate,
                                for: authService.currentUser!,
                                scope: .allFuture,
                                progressVM: progressVM
                            )
                        }
                        pendingVideo = nil
                    }
                    Button("Abbrechen", role: .cancel) { pendingVideo = nil }
                } message: {
                    Text("Soll \"\(pendingVideo?.title ?? "")\" nur heute oder für alle \(pendingRecurrenceRule.rawValue.lowercased()) Termine eingeplant werden?")
                }
                .confirmationDialog(
                    "Video entfernen",
                    isPresented: $showDeleteScopeDialog,
                    titleVisibility: .visible
                ) {
                    Button("Nur diesen Tag", role: .destructive) {
                        if let schedule = pendingDeleteSchedule {
                            settingsVM.removeScheduleWithScope(
                                schedule,
                                for: authService.currentUser!,
                                scope: .onlyToday,
                                progressVM: progressVM
                            )
                        }
                        pendingDeleteSchedule = nil
                    }
                    Button("Alle zukünftigen Termine", role: .destructive) {
                        if let schedule = pendingDeleteSchedule {
                            settingsVM.removeScheduleWithScope(
                                schedule,
                                for: authService.currentUser!,
                                scope: .allFuture,
                                progressVM: progressVM
                            )
                        }
                        pendingDeleteSchedule = nil
                    }
                    Button("Abbrechen", role: .cancel) { pendingDeleteSchedule = nil }
                } message: {
                    Text("Soll \"\(pendingDeleteSchedule?.video?.title ?? "")\" nur heute oder für alle zukünftigen Termine entfernt werden?")
                }

                   .onAppear {
                               guard let user = currentUser else {
                                   print("⚠️ HomeView: Kein User eingeloggt")
                                   return
                               }
                               print("🏠 HomeView onAppear - currentUser.email: '\(user.email)'")
                               progressVM.loadToday(for: user)
                           }
        }
    }
    
    
    @ToolbarContentBuilder
    var toolbarContent: some ToolbarContent {
        // LINKS: Plus + Filter
        ToolbarItem(placement: .topBarLeading) {
            HStack(spacing: 12) {
                
            }
        }
        
        // RECHTS: Profile-Menü
        ToolbarItem(placement: .topBarTrailing) {
            Menu {
                Button("Profil") {
                    activeSheet = .profile                 }
                Button("Einstellungen") {
                    activeSheet = .settings
                }
            } label: {
                // ✅ PROFILBILD STATT ICON
                           if let user = authService.currentUser,
                              let imageData = user.profileImage,
                              let uiImage = UIImage(data: imageData) {
                               Image(uiImage: uiImage)
                                   .resizable()
                                   .scaledToFill()
                                   .frame(width: 35, height: 35)
                                   .clipShape(Circle())
                           } else {
                               Circle()
                                   .fill(Color.accentColor.opacity(0.3))
                                   .frame(width: 35, height: 35)
                                   .overlay(
                                       Text(authService.currentUser?.initials ?? "?")
                                           .font(.system(size: 14, weight: .bold))
                                           .foregroundStyle(Color.accentColor)
                                   )
                           }
            }
        }
    }
}
#Preview("CalendarView") {
    let config = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(
        for: VideoSchedule.self, Appointment.self,
        configurations: config
    )
    
    let context = ModelContext(container)
    
    let authService = AuthService(authServiceProtocol: MockAuthService())
    let settingsVM = SettingsViewModel(modelContext: context, authService: authService)
    let progressVM = ProgressViewModel(modelContext: context)
    let appointmentVM = AppDependencies.shared.appointmentViewModel
    
    // ✅ CalendarViewModel MIT modelContext
    let calendarVM = CalendarViewModel(modelContext: context)
    
    let videoLibraryVM = VideoLibraryViewModel(
        repository: VideoRepository(modelContext: context, storageService: .shared, thumbnailService: .shared),
        modelContext: context,
        storageService: .shared
    )
    
    let previewRepo = VideoRepository(modelContext: context, storageService: .shared, thumbnailService: .shared)
    
    CalendarView(repository: previewRepo)
        .environmentObject(authService)
        .environmentObject(progressVM)
        .environmentObject(appointmentVM)
        .environmentObject(calendarVM)
        .environmentObject(settingsVM)
        .environmentObject(videoLibraryVM)
        .modelContainer(container)
        .frame(height: 900)
}
