
import SwiftUI
import SwiftData

struct HomeView: View {
    
    
    @EnvironmentObject var authService: AuthService

    @EnvironmentObject var progressVM: ProgressViewModel
    @EnvironmentObject var videoLibraryVM: VideoLibraryViewModel
    @EnvironmentObject var settingsVM: SettingsViewModel
    @EnvironmentObject var profileVM: ProfileViewModel

    
    @State private var pendingVideo: Video?
    @State private var pendingDate: Date = Date()
    @State private var showScopeDialog = false
    @State private var pendingRecurrenceRule: RecurrenceRule = .single
    @State private var pendingDeleteSchedule: VideoSchedule?
    @State private var showDeleteScopeDialog = false
    
    
    
    @State private var videoPlayerItem: VideoPlayerItem?
    



    @State private var editingScheduleId: UUID?  // ← Für EDIT!
    @State private var isEditingMode = false
    @State private var activeSheet: SheetType?
    @State private var selectedVideoForConfig: Video?
    @State private var playbackSettings = PlaybackSettings()
    
   


    enum SheetType: Identifiable {
        case
        library,
        profile,
        settings
        var id: Self { self }
    }

    // ✅ Computed property für sicheren Zugriff
       private var currentUser: User? {
           authService.currentUser
       }
    
    
    var body: some View {
     
        ScrollView {
            VStack(spacing: 20) {
                
                // compactRingView
                DailyProgressCard()
                    .environmentObject(settingsVM)
                
                // Liste der heutigen Videos
                VStack(spacing: 4) { 
                ExercisesSection(
                    onToggleCompletion: { schedule in
                        progressVM.toggleCompletion(schedule, for: authService.currentUser!)
                    },
                    onDelete: { schedule in
                        let rule = settingsVM.preferences
                            .getGoalFor(dayOfWeek: schedule.dayOfWeek)?.recurrenceRule ?? .single
                        
                        if rule == .single || !schedule.isAutoGenerated {
                            progressVM.removeSchedule(schedule, for: authService.currentUser!)
                        } else {
                            pendingDeleteSchedule = schedule
                            showDeleteScopeDialog = true
                        }
                    },
                    onConfig: { schedule in
                        editingScheduleId = schedule.id
                        selectedVideoForConfig = schedule.video ?? Video.previewMobility
                        playbackSettings = PlaybackSettings(
                            repetitions: schedule.customRepetitions ?? 3,
                            pauseSeconds: schedule.customPauseSeconds ?? 30,
                            loopDurationSeconds: schedule.customLoopDurationSeconds
                                ?? schedule.video?.loopDurationSeconds
                                ?? 120
                        )
                    },
                    
                    
                    
                    onPlay: { schedule, video in
                        videoPlayerItem = VideoPlayerItem(
                            video: video,
                            scheduleId: schedule.id
                        )
                    },
                    onAddVideo: {
                        activeSheet = .library  // ← Sheet öffnet sich!
                    }
                )
                
                
               
            }
        }
                .padding()
            }
        .background(Color(.systemGroupedBackground))
            .navigationTitle("Heute")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Menu {
                        Button("Profil") { activeSheet = .profile }
                            Button("Einstellungen") { activeSheet = .settings }
                    } label: {
                        // ✅ PROFILBILD STATT ICON
                                   if let user = authService.currentUser,
                                      let imageData = user.profileImage,
                                      let uiImage = UIImage(data: imageData) {
                                       Image(uiImage: uiImage)
                                           .resizable()
                                           .scaledToFill()
                                           .frame(width: 35, height: 35)
                                           .clipShape(Circle())
                                   } else {
                                       Circle()
                                           .fill(Color.accentColor.opacity(0.3))
                                           .frame(width: 35, height: 35)
                                           .overlay(
                                               Text(authService.currentUser?.initials ?? "?")
                                                   .font(.system(size: 14, weight: .bold))
                                                   .foregroundStyle(Color.accentColor)
                                           )
                                   }
                    }
                }
            }

            .sheet(item: $activeSheet) { sheet in
                switch sheet {
                case .settings:
                    SettingsView() // ← user Parameter
                        .environmentObject(settingsVM)   // ← VM injizieren!
                        .environment(\.modelContext, settingsVM.modelContext)
                        .onDisappear {
                            progressVM.loadToday(for: authService.currentUser!)
                        }
                        
                case .profile:
                    ProfileView()
                        .environmentObject(authService)
                        .environment(\.modelContext, profileVM.modelContext)
                case .library:
                    NavigationStack {
                        LibraryView(
                            // ✅ NEU
                            onVideoSelected: { video in
                                activeSheet = nil
                                
                                DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                                    pendingDate = Date()
                                    editingScheduleId = nil
                                    playbackSettings = PlaybackSettings(
                                        repetitions: video.defaultRepetitions,
                                        pauseSeconds: video.defaultPauseSeconds,
                                        loopDurationSeconds: video.loopDurationSeconds
                                    )
                                    selectedVideoForConfig = video  // ← öffnet Config-Sheet
                                }
                            }
                        )
                        .environmentObject(authService)
                        .environmentObject(videoLibraryVM)
                        .environmentObject(settingsVM)
                    
                    }
        
                }
        }
        
            .sheet(item: $selectedVideoForConfig) { video in
                VideoQuickConfigSheet(
                    video: video,
                    initialRepetitions: playbackSettings.repetitions,
                    initialLoopDuration: playbackSettings.loopDurationSeconds,
                    initialPause: playbackSettings.pauseSeconds,
                    onAdd: { reps, loopDuration, pause in
                        if let scheduleId = editingScheduleId,
                           let schedule = progressVM.todaysSchedules.first(where: { $0.id == scheduleId }) {
                            // Bestehendes Schedule bearbeiten
                            schedule.customRepetitions = reps
                            schedule.customPauseSeconds = pause
                            schedule.customLoopDurationSeconds = loopDuration
                            progressVM.updateSchedule(schedule, for: authService.currentUser!)
                        } else {
                            // ✅ Neues Video hinzufügen
                            let rule = settingsVM.recurrenceRule(for: pendingDate)
                            if rule == .single {
                                progressVM.addVideo(
                                    video,
                                    to: pendingDate,
                                    for: authService.currentUser!,
                                    customRepetitions: reps,
                                    customPauseSeconds: pause,
                                    customLoopDuration: loopDuration
                                )
                            } else {
                                pendingVideo = video
                                pendingRecurrenceRule = rule
                                showScopeDialog = true
                            }
                        }
                        selectedVideoForConfig = nil
                        editingScheduleId = nil
                    
                    },
                    onCancel: {
                        selectedVideoForConfig = nil
                        editingScheduleId = nil
                    }
                )
            }
        // ⭐️ VIDEO PLAYER SHEET
        // ✅ Neu
        .sheet(item: $videoPlayerItem) { item in
            VideoPlayerView(
                video: item.video,
                scheduleId: item.scheduleId,
                progressViewModel: progressVM,
                authService: authService
            )
        }

        
        // In HomeView nach dem letzten .sheet
        .confirmationDialog(
            "Video einplanen",
            isPresented: $showScopeDialog,
            titleVisibility: .visible
        ) {
            Button("Nur für diesen Tag") {
      
                if let video = pendingVideo {
                    print("🎯 Scope: onlyToday, date: \(pendingDate), video: \(video.title)")
                    settingsVM.addVideoWithScope(
                        video,
                        to: pendingDate,
                        for: authService.currentUser!,
                        scope: .onlyToday,
                        progressVM: progressVM
                    )
                }
                pendingVideo = nil
            }
            Button("Für alle \(pendingRecurrenceRule.rawValue) Termine") {
                if let video = pendingVideo {
                    settingsVM.addVideoWithScope(
                        video,
                        to: pendingDate,
                        for: authService.currentUser!,
                        scope: .allFuture,
                        progressVM: progressVM
                    )
                }
                pendingVideo = nil
            }
            Button("Abbrechen", role: .cancel) { pendingVideo = nil }
        } message: {
            Text("Soll \"\(pendingVideo?.title ?? "")\" nur heute oder für alle \(pendingRecurrenceRule.rawValue.lowercased()) Termine eingeplant werden?")
        }
        .confirmationDialog(
            "Video entfernen",
            isPresented: $showDeleteScopeDialog,
            titleVisibility: .visible
        ) {
            Button("Nur diesen Tag", role: .destructive) {
                if let schedule = pendingDeleteSchedule {
                    settingsVM.removeScheduleWithScope(
                        schedule,
                        for: authService.currentUser!,
                        scope: .onlyToday,
                        progressVM: progressVM
                    )
                }
                pendingDeleteSchedule = nil
            }
            Button("Alle zukünftigen Termine", role: .destructive) {
                if let schedule = pendingDeleteSchedule {
                    settingsVM.removeScheduleWithScope(
                        schedule,
                        for: authService.currentUser!,
                        scope: .allFuture,
                        progressVM: progressVM
                    )
                }
                pendingDeleteSchedule = nil
            }
            Button("Abbrechen", role: .cancel) { pendingDeleteSchedule = nil }
        } message: {
            Text("Soll \"\(pendingDeleteSchedule?.video?.title ?? "")\" nur heute oder für alle zukünftigen Termine entfernt werden?")
        }

            .onAppear {
                      guard let user = currentUser else {
                          print("⚠️ HomeView: Kein User eingeloggt")
                          return
                      }
                      progressVM.selectedDate = Date()
                      print("🏠 HomeView onAppear - currentUser.email: '\(user.email)'")
                      progressVM.loadHome(for: user)
                  }

            
    }
    
/*
    // ✅ SICHERE Dauer-Berechnung
    private func calculateTotalDuration(schedule: any PersistentModel, video: Video) -> String {
        // Annahme: schedule hat repetitions, pauseSeconds, loopDurationSeconds als Int
        let loopDuration = 120  // Fallback
        let repetitions = 3     // Fallback
        let pauseSeconds = 30   // Fallback
        
        let totalSeconds = (loopDuration * repetitions) + max(0, (repetitions - 1) * pauseSeconds)
        
        let minutes = totalSeconds / 60
        let secs = totalSeconds % 60
        return secs > 0 ? "\(minutes):\(String(format: "%02d", secs)) Min" : "\(minutes) Min"
    }

*/
}
#Preview {
    let config = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(
        for: VideoSchedule.self, Appointment.self,
        configurations: config
    )
    
    let context = ModelContext(container)
    let authService = AuthService(authServiceProtocol: MockAuthService(modelContext: context))
    let repository = VideoScheduleRepository(modelContext: context)
      let progressVM = ProgressViewModel(authService: authService, repository: repository)
    let appointmentVM = PreviewHelper.createAppointmentViewModel()
    
    let videoLibraryVM = VideoLibraryViewModel(
        repository: VideoRepository(modelContext: context, storageService: .shared, thumbnailService: .shared),
        modelContext: context,
        authService: authService
    )
    let settingsVM = SettingsViewModel(modelContext: context, authService: authService)

    HomeView()
        .environmentObject(authService)
        .environmentObject(progressVM)
        .environmentObject(videoLibraryVM)
        .environmentObject(settingsVM)
        .environmentObject(appointmentVM)
        .modelContainer(container)
}
