//
//  CalendarDayView.swift
//  Agil10.0
//
//  Created by Christiane Roth on 12.04.26.
//


import SwiftUI
import SwiftData

struct CalendarDayView: View {
    @EnvironmentObject var session: SessionManager
    @EnvironmentObject var progressVM: ProgressViewModel
    @EnvironmentObject var appointmentViewModel: AppointmentViewModel
    @EnvironmentObject var calendarViewModel: CalendarViewModel
    @EnvironmentObject var videoLibraryVM: VideoLibraryViewModel
    @EnvironmentObject private var settingsVM: SettingsViewModel
    @EnvironmentObject var profileVM: ProfileViewModel
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) var modelContext
    @EnvironmentObject var themeManager: ThemeManager
    
    @Query private var allAppointments: [Appointment]
    
    @State private var videoPlayerItem: VideoPlayerItem?
    @State private var pendingVideo: Video?
    @State private var pendingDate: Date = Date()
    @State private var showScopeDialog = false
    @State private var pendingRecurrenceRule: RecurrenceRule = .single
    @State private var pendingDeleteSchedule: VideoSchedule?
    @State private var showDeleteScopeDialog = false
    @State private var editingScheduleId: UUID?
    @State private var activeSheet: SheetType?
    @State private var selectedVideoForConfig: Video?
    @State private var playbackSettings = PlaybackSettings()
    @State private var pendingReps: Int = 1
    @State private var pendingPause: Int = 30
    @State private var pendingLoopDuration: Int = 120
    @State private var selectedAppointment: Appointment? = nil
    
    @State private var swipeDirection: SwipeDirection? = nil
    @State private var pendingEditWeightKg: Int? = nil
    @State private var expertSession: ExpertSessionItem?
    
    private var editingSchedule: VideoSchedule? {
        guard let id = editingScheduleId else { return nil }
        return progressVM.todaysSchedules.first(where: { $0.id == id })
    }
    
    
    enum SwipeDirection { case horizontal, vertical }
    
    enum SheetType: Identifiable {
        case videoPicker, appointments, settings
        var id: Self { self }
    }
    
    private var currentUser: User? { session.currentUser }
    
    private var userAppointments: [Appointment] {
        guard let userId = currentUser?.id else { return [] }
        return allAppointments.filter {
            $0.userId == userId &&
            $0.date > Date().addingTimeInterval(-86400) &&
            $0.status != .cancelled
        }
    }

    /// Prüft, ob an einem bestimmten Tag ein Termin liegt (für WeekStripView).
    private func hasAppointment(on date: Date) -> Bool {
        guard let userId = currentUser?.id else { return false }
        return allAppointments.contains {
            $0.userId == userId &&
            $0.status != .cancelled &&
            Calendar.current.isDate($0.date, inSameDayAs: date)
        }
    }
    
    private func handleDelete(_ schedule: VideoSchedule) {
        if schedule.planMode == "single" || !schedule.isAutoGenerated {
            // Nur diesen einen löschen
            progressVM.removeSchedule(schedule, for: session.currentUser!)
        } else {
            // daily oder weekly → fragen
            pendingDeleteSchedule = schedule
            showDeleteScopeDialog = true
        }
    }
    
    private func handleConfig(_ schedule: VideoSchedule) {
        editingScheduleId = schedule.id
        selectedVideoForConfig = schedule.video
        
        let video = schedule.video
        playbackSettings = PlaybackSettings(
            repetitions: schedule.customRepetitions
                ?? video?.defaultRepetitions
                ?? 3,
            pauseSeconds: schedule.customPauseSeconds
                ?? video?.defaultPauseSeconds
                ?? 30,
            loopDurationSeconds: schedule.customLoopDurationSeconds
                ?? video?.loopDurationSeconds
                ?? 120
        )
        pendingEditWeightKg = schedule.weightKg
    }
    
    private func handlePlay(_ schedule: VideoSchedule, _ video: Video) {
        let expertEnabled = settingsVM.preferences.expertModeEnabled
        
        if expertEnabled, let tempo = video.tempoProtocol {
            expertSession = ExpertSessionItem(
                schedule: schedule,
                video: video,
                tempoProtocol: tempo
            )
        } else {
            videoPlayerItem = VideoPlayerItem(video: video, scheduleId: schedule.id)
        }
    }
    
    var body: some View {
        ScrollView {
            VStack(spacing: 16) {
                
                WeekStripView(
                    selectedDate: calendarViewModel.selectedDate,
                    weekDays: calendarViewModel.currentWeekDays,
                    hasAppointment: { hasAppointment(on: $0) },
                    hasExercise: { calendarViewModel.hasSchedules(on: $0) },
                    onSelect: { calendarViewModel.select(date: $0) },
                    onSwipeWeek: { direction in
                        if direction < 0 {
                            calendarViewModel.previousWeek()
                        } else {
                            calendarViewModel.nextWeek()
                        }
                    }
                )
          
                Divider()
                        .padding(.top, -16)
                                 
                
                SelectedDateInfoView(
                    selectedDate: calendarViewModel.selectedDate,
                    appointments: userAppointments.filter {
                        Calendar.current.isDate($0.date, inSameDayAs: calendarViewModel.selectedDate)
                    },
                    onAddAppointment: { activeSheet = .appointments },
                    onTapAppointment: { selectedAppointment = $0 }
                )
                .padding(.horizontal, 16)
                .padding(.top, 12)
                
                ExercisesForDateView(
                    selectedDate: calendarViewModel.selectedDate,
                    onAddExercise: { activeSheet = .videoPicker },
                    onConfig: { handleConfig($0) },
                    onPlay: { handlePlay($0, $1) },
                    onDelete: { handleDelete($0) }
                )
            }
            .padding(.bottom, 20)
            .contentShape(Rectangle())
            .simultaneousGesture(
                DragGesture(minimumDistance: 20)
                    .onChanged { value in
                        if swipeDirection == nil {
                            let dx = abs(value.translation.width)
                            let dy = abs(value.translation.height)
                            if dx > dy && dx > 10 {
                                swipeDirection = .horizontal
                            } else if dy > dx {
                                swipeDirection = .vertical
                            }
                        }
                    }
                    .onEnded { value in
                        defer { swipeDirection = nil }
                        guard swipeDirection == .horizontal else { return }
                        
                        
                        
                    }
            )
            
            
        }
        
        .background(Color(.systemGroupedBackground))
        .navigationTitle("")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .tabBar)
        .onChange(of: calendarViewModel.selectedDate) { _, newDate in
            if let user = session.currentUser {
                progressVM.loadToday(for: user, date: newDate)
            }
        }
        // ✅ NEU direkt darunter hinzufügen:
        .onChange(of: settingsVM.preferences.activeMode) { _, _ in
            guard let user = session.currentUser else { return }
            progressVM.loadToday(for: user, date: calendarViewModel.selectedDate)
        }
        .onAppear {
            guard let user = currentUser else { return }
            progressVM.loadToday(for: user, date: calendarViewModel.selectedDate)
        }
        .fullScreenCover(item: $activeSheet) { sheet in
            switch sheet {
            case .settings:
                SettingsView()
                    .environmentObject(settingsVM)
                    .environmentObject(videoLibraryVM)
                    .environmentObject(progressVM)
                    .environment(\.modelContext, settingsVM.modelContext)
                    .onDisappear {
                        progressVM.loadToday(for: session.currentUser!)
                    }
            case .videoPicker:
                VideoPickerSheet { video in
                    activeSheet = nil
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                        pendingDate = calendarViewModel.selectedDate
                        editingScheduleId = nil
                        playbackSettings = PlaybackSettings(
                            repetitions: video.defaultRepetitions,
                            pauseSeconds: video.defaultPauseSeconds,
                            loopDurationSeconds: video.loopDurationSeconds
                        )
                        selectedVideoForConfig = video
                    }
                }
                .environmentObject(videoLibraryVM)
                .environmentObject(session)
            case .appointments:
                ManualAppointmentEntryView()
            }
        }
        .fullScreenCover(item: $selectedVideoForConfig) { video in
            VideoQuickConfigSheet(
                video: video,
                activeMode: settingsVM.preferences.activeMode,
                expertModeEnabled: settingsVM.preferences.expertModeEnabled,
                initialRepetitions: playbackSettings.repetitions,
                initialLoopDuration: playbackSettings.loopDurationSeconds,
                initialPause: playbackSettings.pauseSeconds,
                initialWeightKg: pendingEditWeightKg,
                initialSets: editingSchedule?.sets,
                initialRepsPerSet: editingSchedule?.reps,
                initialExpertPauseSeconds: editingSchedule?.expertPauseSeconds,
                onAdd: { reps, loopDuration, pause, mode, weight, sets, repsPerSet, expertPause in
                    if let scheduleId = editingScheduleId,
                       let schedule = progressVM.todaysSchedules.first(where: { $0.id == scheduleId }) {
                        if settingsVM.preferences.expertModeEnabled,
                           schedule.video?.tempoProtocol?.subtype == .dynamic {
                            schedule.sets = sets
                            schedule.reps = repsPerSet
                            schedule.expertPauseSeconds = expertPause
                        } else {
                            schedule.customRepetitions = reps
                            schedule.customPauseSeconds = pause
                            schedule.customLoopDurationSeconds = loopDuration
                        }
                        schedule.weightKg = weight
                        progressVM.updateSchedule(schedule, for: session.currentUser!)
                    } else {
                        progressVM.addVideo(
                            video,
                            to: pendingDate,
                            for: session.currentUser!,
                            planMode: mode,
                            activeMode: settingsVM.preferences.activeMode,
                            customRepetitions: reps,
                            customPauseSeconds: pause,
                            customLoopDuration: loopDuration,
                            sets: sets,
                            reps: repsPerSet,
                            expertPauseSeconds: expertPause,
                            weightKg: weight
                        )
                        progressVM.loadToday(for: session.currentUser!, date: pendingDate)
                    }
                    
                    selectedVideoForConfig = nil
                    editingScheduleId = nil
                    pendingEditWeightKg = nil
                },
                onCancel: {
                    selectedVideoForConfig = nil
                    editingScheduleId = nil
                    pendingEditWeightKg = nil
                }
            )
        }
        
        
        
        .sheet(item: $videoPlayerItem) { item in
            VideoPlayerView(
                video: item.video,
                scheduleId: item.scheduleId,
                progressViewModel: progressVM,
                session: session
            )
        }
        
        .sheet(item: $expertSession) { item in
            ExpertModePlayerView(
                video: item.video,
                tempoProtocol: item.tempoProtocol,
                weightKg: item.schedule.weightKg,
                setsOverride: item.schedule.sets,
                repsOverride: item.schedule.reps,
                restOverride: item.schedule.customPauseSeconds,
                lastTrainingTotalKg: nil,
                videoDuringTraining: settingsVM.preferences.videoDuringTraining,
                scheduleId: item.schedule.id,
                progressViewModel: progressVM,
                session: session
            )
        }
        
        .sheet(item: $selectedAppointment) { appointment in
            AppointmentDetailView(appointment: appointment)
                .environmentObject(session)
                .environmentObject(appointmentViewModel)
        }
        .confirmationDialog("Video entfernen", isPresented: $showDeleteScopeDialog, titleVisibility: .visible) {
            Button("Nur diesen Tag", role: .destructive) {
                if let schedule = pendingDeleteSchedule {
                    settingsVM.removeScheduleWithScope(schedule, for: session.currentUser!, scope: .onlyToday)
                    progressVM.loadToday(for: session.currentUser!, date: calendarViewModel.selectedDate)
                }
                pendingDeleteSchedule = nil
            }
            Button("Alle zukünftigen Termine", role: .destructive) {
                if let schedule = pendingDeleteSchedule {
                    settingsVM.removeScheduleWithScope(schedule, for: session.currentUser!, scope: .allFuture)
                    progressVM.loadToday(for: session.currentUser!, date: calendarViewModel.selectedDate)
                }
                pendingDeleteSchedule = nil
            }
            Button("Abbrechen", role: .cancel) { pendingDeleteSchedule = nil }
        } message: {
            Text("Soll \"\(pendingDeleteSchedule?.video?.title ?? "")\" nur heute oder für alle zukünftigen Termine entfernt werden?")
        }
        
        .overlay(alignment: .bottomLeading) {
            if !Calendar.current.isDateInToday(calendarViewModel.selectedDate) {
                Button {
                    calendarViewModel.select(date: Date())
                } label: {
                    Label("Heute", systemImage: "calendar.circle.fill")
                        .font(.subheadline)
                        .fontWeight(.semibold)
                        .padding(.horizontal, 14)
                        .padding(.vertical, 8)
                        .glassEffect(in: Capsule())
                }
                .buttonStyle(.borderless)
                .padding(.bottom, 16)
                .padding(.leading, 16)
                .transition(.scale.combined(with: .opacity))
            }
        }
        .animation(.spring(response: 0.35), value: calendarViewModel.selectedDate)
    }
}
