
import SwiftUI
import SwiftData

struct HomeView: View {
    
    
    @EnvironmentObject var session: SessionManager

    @EnvironmentObject var progressVM: ProgressViewModel
    @EnvironmentObject var videoLibraryVM: VideoLibraryViewModel
    @EnvironmentObject var settingsVM: SettingsViewModel
    @EnvironmentObject var profileVM: ProfileViewModel
    @EnvironmentObject var appointmentViewModel: AppointmentViewModel
    @EnvironmentObject var themeManager: ThemeManager
    
 
    @State private var pendingDate: Date = Date()
   
 
    @State private var pendingDeleteSchedule: VideoSchedule?
    @State private var showDeleteScopeDialog = false
    
    
    @State private var videoPlayerItem: VideoPlayerItem?
    



    @State private var editingScheduleId: UUID?  // ← Für EDIT!
    @State private var isEditingMode = false
    @State private var activeSheet: SheetType?
    @State private var selectedVideoForConfig: Video?
    @State private var playbackSettings = PlaybackSettings()
    
    @State private var showPlayAllSession = false
    
    @State private var selectedAppointment: Appointment? = nil
    
    @State private var pendingEditWeightKg: Int? = nil
    @State private var expertSession: ExpertSessionItem?
    
    private var editingSchedule: VideoSchedule? {
        guard let id = editingScheduleId else { return nil }
        return progressVM.todaysSchedules.first(where: { $0.id == id })
    }
    
    
    enum SheetType: Identifiable {
        case
        videoPicker,
        profile
        var id: Self { self }
    }

    // ✅ Computed property für sicheren Zugriff
       private var currentUser: User? {
           session.currentUser
       }
    
    
    var body: some View {
        let _ = print("🔍 HomeView workoutModus: \(settingsVM.preferences.workoutModus)")
                            ScrollView {
            VStack(spacing: 20) {
                
                // compactRingView
                DailyProgressCard()
                    .environmentObject(settingsVM)
                
                // Liste der heutigen Videos
                VStack(spacing: 4) { 
                ExercisesSection(
                    onToggleCompletion: { schedule in
                        progressVM.toggleCompletion(schedule, for: session.currentUser!)
                    },
                    onDelete: { schedule in
                        if schedule.planMode == "single" || !schedule.isAutoGenerated {
                            progressVM.removeSchedule(schedule, for: session.currentUser!)
                        } else {
                            pendingDeleteSchedule = schedule
                            showDeleteScopeDialog = true
                        }
                    },
                    onConfig: { schedule in
                        editingScheduleId = schedule.id
                        selectedVideoForConfig = schedule.video ?? Video.previewMobility
                        
                        let video = schedule.video
                        playbackSettings = PlaybackSettings(
                            repetitions: schedule.customRepetitions
                                ?? video?.defaultRepetitions
                                ?? 3,
                            pauseSeconds: schedule.customPauseSeconds
                                ?? video?.defaultPauseSeconds
                                ?? 30,
                            loopDurationSeconds: schedule.customLoopDurationSeconds
                                ?? video?.loopDurationSeconds
                                ?? 120
                        )
                        pendingEditWeightKg = settingsVM.preferences.workoutModus == .mobility
                                                    ? schedule.mobilityWeightKg
                                                    : schedule.weightKg
                                            },
                

                    // NEU:
                    onPlay: { schedule, video in
                                            let modus = settingsVM.preferences.workoutModus
                                            let style: SessionCompletionStyle =
                                                (modus == .mobility) ? .feedbackScale : .starRating

                                            print("🎯 onPlay — modus: \(modus), style: \(style), pillCapable: \(schedule.isExpertDynamicCapable)")

                                      

                                            // Pill-fähig = Kraft + dynamisches TempoProtocol.
                                            let pillCapable = schedule.isExpertDynamicCapable

                                            // Pill-Player nur in Expert/Mobility UND wenn das Video pill-fähig ist.
                                            let usesPill = pillCapable && (modus == .expert || modus == .mobility)

                                            if usesPill {
                                                // Mobility: frisches 3-0-3 / 3 Sätze / 20 Wdh.
                                                // Expert: das gespeicherte TempoProtocol des Videos.
                                                let tempo: TempoProtocol
                                                if modus == .mobility {
                                                    tempo = TempoProtocol(
                                                        concentricSec: 3, holdSec: 0, eccentricSec: 3,
                                                        sets: 3, reps: 20,
                                                        restBetweenSetsSec: 60,
                                                        subtype: .dynamic
                                                    )
                                                } else {
                                                    tempo = video.tempoProtocol ?? TempoProtocol()
                                                }
                                                expertSession = ExpertSessionItem(
                                                    schedule: schedule,
                                                    video: video,
                                                    tempoProtocol: tempo,
                                                    completionStyle: style
                                                )
                                            } else {
                                                // Standard immer hier; Expert/Mobility bei nicht-pill-fähigen Videos.
                                                videoPlayerItem = VideoPlayerItem(
                                                    video: video,
                                                    scheduleId: schedule.id,
                                                    completionStyle: style
                                                )
                                            }
                                        },
                    
                    
                    onAddVideo: {
                        activeSheet = .videoPicker
                    },
                    onRate: { schedule, rating in
                           schedule.rating = rating
                           progressVM.updateSchedule(schedule, for: session.currentUser!)
                       },
                    onMobilityFeedback: { schedule, value in
                        schedule.mobilityFeedback = value
                        progressVM.updateSchedule(schedule, for: session.currentUser!)
                    },
                    
                    onPlayAll: {
                        showPlayAllSession = true
                    }
                )
                
                
               
            }
        }
                .padding()
            }
      
        
        .background(Color(.systemGroupedBackground))
            .navigationTitle("")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
        
                    Button {
                           activeSheet = .profile
                    } label: {
                        // ✅ PROFILBILD STATT ICON
                                   if let user = session.currentUser,
                                      let imageData = user.profileImage,
                                      let uiImage = UIImage(data: imageData) {
                                       Image(uiImage: uiImage)
                                           .resizable()
                                           .scaledToFill()
                                           .frame(width: 35, height: 35)
                                           .clipShape(Circle())
                                   } else {
                                       Circle()
                                           .fill(themeManager.currentTheme.accentColor.opacity(0.3))
                                           .frame(width: 35, height: 35)
                                           .overlay(
                                               Text(session.currentUser?.initials ?? "?")
                                                   .font(.system(size: 14, weight: .bold))
                                                   .foregroundStyle(themeManager.currentTheme.accentColor)
                                           )
                                   }
                    }
                }
            }
        

            .sheet(item: $activeSheet) { sheet in
                switch sheet {
                    
                case .profile:
                    ProfileView()
                        .environmentObject(session)
                        .environmentObject(settingsVM)  
                        .environment(\.modelContext, profileVM.modelContext)
                case .videoPicker:
                    VideoPickerSheet { video in
                        activeSheet = nil
                        DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                            pendingDate = Date()
                            editingScheduleId = nil
                            playbackSettings = PlaybackSettings(
                                repetitions: video.defaultRepetitions,
                                pauseSeconds: video.defaultPauseSeconds,
                                loopDurationSeconds: video.loopDurationSeconds
                            )
                            selectedVideoForConfig = video
                        }
                    }
                    .environmentObject(videoLibraryVM)
                    .environmentObject(session)
                }
            }
        
            .fullScreenCover(item: $selectedVideoForConfig) { video in
                VideoQuickConfigSheet(
                                  video: video,
                                  activeMode: settingsVM.preferences.activeMode,
                                  workoutModus: settingsVM.preferences.workoutModus,
                                  initialRepetitions: playbackSettings.repetitions,
                                  initialLoopDuration: playbackSettings.loopDurationSeconds,
                                  initialPause: playbackSettings.pauseSeconds,
                                  initialWeightKg: pendingEditWeightKg,
                                  initialSets: settingsVM.preferences.workoutModus == .mobility
                                      ? editingSchedule?.mobilitySets
                                      : editingSchedule?.sets,
                                  initialRepsPerSet: settingsVM.preferences.workoutModus == .mobility
                                      ? editingSchedule?.mobilityReps
                                      : editingSchedule?.reps,
                                  initialExpertPauseSeconds: settingsVM.preferences.workoutModus == .mobility
                                      ? editingSchedule?.mobilityPauseSeconds
                                      : editingSchedule?.expertPauseSeconds,
                                  onAdd: { reps, loopDuration, pause, mode, weight, sets, repsPerSet, expertPause in
                                                          print("🏋️ HomeView onAdd erhält weight=\(String(describing: weight))")
                                                          print("📥 onAdd — sets:\(String(describing: sets)) repsPerSet:\(String(describing: repsPerSet)) editingId:\(String(describing: editingScheduleId))")
                        if let scheduleId = editingScheduleId,
                                                  let schedule = progressVM.todaysSchedules.first(where: { $0.id == scheduleId }) {
                                                   // Bestehenden Schedule editieren — nur die Felder des aktiven Modus.
                                                   let modus = settingsVM.preferences.workoutModus
                                                   let isPillCapable = schedule.video?.tempoProtocol?.subtype == .dynamic

                            if modus == .expert, isPillCapable {
                                                                                   schedule.sets = sets
                                                                                   schedule.reps = repsPerSet
                                                                                   schedule.expertPauseSeconds = expertPause
                                                                                   schedule.weightKg = weight
                                                                               } else if modus == .mobility, isPillCapable {
                                                                                   schedule.mobilitySets = sets
                                                                                   schedule.mobilityReps = repsPerSet
                                                                                   schedule.mobilityPauseSeconds = expertPause
                                                                                   schedule.mobilityWeightKg = weight
                                                                               } else {
                                                                                   schedule.customRepetitions = reps
                                                                                   schedule.customPauseSeconds = pause
                                                                                   schedule.customLoopDurationSeconds = loopDuration
                                                                                   schedule.weightKg = weight
                                                                               }
                        } else {
                                                    let modus = settingsVM.preferences.workoutModus
                                                    print("🆕 Neu anlegen — modus:\(modus) sets:\(String(describing: sets)) reps:\(String(describing: repsPerSet))")
                                                    progressVM.addVideo(
                                                           video,
                                                           to: pendingDate,
                                                           for: session.currentUser!,
                                                           planMode: mode,
                                                           activeMode: settingsVM.preferences.activeMode,
                                                           customRepetitions: reps,
                                                           customPauseSeconds: pause,
                                                           customLoopDuration: loopDuration,
                                                           sets: modus == .expert ? sets : nil,
                                                           reps: modus == .expert ? repsPerSet : nil,
                                                           expertPauseSeconds: modus == .expert ? expertPause : nil,
                                                           mobilitySets: modus == .mobility ? sets : nil,
                                                           mobilityReps: modus == .mobility ? repsPerSet : nil,
                                                           mobilityPauseSeconds: modus == .mobility ? expertPause : nil,
                                                           mobilityWeightKg: modus == .mobility ? weight : nil,
                                                                                                                     weightKg: modus == .mobility ? nil : weight
                                
                            )
                            progressVM.loadToday(for: session.currentUser!, date: pendingDate)
                        }
                        
                        selectedVideoForConfig = nil
                        editingScheduleId = nil
                        pendingEditWeightKg = nil
                    },
                    onCancel: {
                        selectedVideoForConfig = nil
                        editingScheduleId = nil
                        pendingEditWeightKg = nil
                    }
                )
            }
        
  
    // ⭐️ VIDEO PLAYER SHEET
            .fullScreenCover(item: $videoPlayerItem) { item in
                       VideoPlayerView(
                           video: item.video,
                           scheduleId: item.scheduleId,
                           progressViewModel: progressVM,
                           session: session,
                           completionStyle: item.completionStyle
                       )
                   }
        
        
            .fullScreenCover(item: $expertSession) { item in
                               let modus = settingsVM.preferences.workoutModus
                               ExpertModePlayerView(
                                   video: item.video,
                                   tempoProtocol: item.tempoProtocol,
                                   weightKg: item.schedule.activeWeightKg(modus: modus),
                                   setsOverride: item.schedule.activeSets(modus: modus),
                                   repsOverride: item.schedule.activeReps(modus: modus),
                                   restOverride: item.schedule.activePauseSeconds(modus: modus),
                                   lastTrainingTotalKg: nil,
                                   videoDuringTraining: .toggleable,
                                   completionStyle: item.completionStyle,
                                   scheduleId: item.schedule.id,
                                   progressViewModel: progressVM,
                                   session: session
                               )
                           }
        
        
        
        
        .fullScreenCover(isPresented: $showPlayAllSession) {
            PlayAllSessionView(
                schedules: progressVM.todaysSchedules,
                session: session,
                progressVM: progressVM
            )
            .environmentObject(progressVM)
        }
        
        
        .sheet(item: $selectedAppointment) { appointment in
            AppointmentDetailView(appointment: appointment)
                .environmentObject(session)
                .environmentObject(appointmentViewModel)
        }
        
        .confirmationDialog("Video entfernen", isPresented: $showDeleteScopeDialog, titleVisibility: .visible) {
            Button("Nur heute", role: .destructive) {
                if let schedule = pendingDeleteSchedule {
                    settingsVM.removeScheduleWithScope(schedule, for: session.currentUser!, scope: .onlyToday)
                    progressVM.loadToday(for: session.currentUser!, date: Date())
                }
                pendingDeleteSchedule = nil
            }
            Button("Alle zukünftigen Termine", role: .destructive) {
                if let schedule = pendingDeleteSchedule {
                    settingsVM.removeScheduleWithScope(schedule, for: session.currentUser!, scope: .allFuture)
                    progressVM.loadToday(for: session.currentUser!, date: Date())
                }
                pendingDeleteSchedule = nil
            }
            Button("Abbrechen", role: .cancel) { pendingDeleteSchedule = nil }
        } message: {
            Text("Soll \"\(pendingDeleteSchedule?.video?.title ?? "")\" nur heute oder für alle zukünftigen Termine entfernt werden?")
        }
        
       
            .onAppear {
                      guard let user = currentUser else {
                          print("⚠️ HomeView: Kein User eingeloggt")
                          return
                      }
                      progressVM.selectedDate = Date()
                      print("🏠 HomeView onAppear - currentUser.email: '\(user.email)'")
                      progressVM.loadHome(for: user)
                  }

            
    }
    
}

#Preview {
    let config = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(
        for: VideoSchedule.self, Video.self, User.self,
        configurations: config
    )
    let context = ModelContext(container)
    let userRepository = UserRepository(modelContext: context)
    let authenticator = LocalAuthBiometricAuthenticator()
    let preferences = UserDefaultsBiometricPreferences()
    let unlockUseCase = UnlockAppUseCase(
        authenticator: authenticator,
        preferences: preferences
    )
    let sessionManager = SessionManager(
                authService: LocalAuthService(),
                userRepository: userRepository,
        unlockUseCase: unlockUseCase,
        preferences: preferences
    )
    

    let repository = VideoScheduleRepository(modelContext: context)
    let settingsVM = SettingsViewModel(
        modelContext: context,
        session: sessionManager,
        addScheduleUseCase: AddScheduleUseCase(repository: repository),
        removeScheduleUseCase: RemoveScheduleUseCase(repository: repository)
    )
    let progressVM = ProgressPreviewHelper.makeProgressVM(context: context)

    let videoLibraryVM = VideoLibraryViewModel(
        repository: VideoRepository(
            modelContext: context,
            storageService: .shared,
            thumbnailService: .shared
        ),
        modelContext: context,
        session: sessionManager
    )
    let profileVM = ProfileViewModel(
        userRepository: UserRepository(modelContext: context),
        session: sessionManager
    )

    NavigationStack {
        HomeView()
            .environmentObject(sessionManager)
            .environmentObject(progressVM)
            .environmentObject(videoLibraryVM)
            .environmentObject(settingsVM)
            .environmentObject(profileVM)
            .modelContainer(container)
    }
}
