
import SwiftUI
import SwiftData

struct HomeView: View {
    
    
    @EnvironmentObject var session: SessionManager

    @EnvironmentObject var progressVM: ProgressViewModel
    @EnvironmentObject var videoLibraryVM: VideoLibraryViewModel
    @EnvironmentObject var settingsVM: SettingsViewModel
    @EnvironmentObject var profileVM: ProfileViewModel

    
    @State private var pendingVideo: Video?
    @State private var pendingDate: Date = Date()
    @State private var showScopeDialog = false
    @State private var pendingRecurrenceRule: RecurrenceRule = .single
    @State private var pendingDeleteSchedule: VideoSchedule?
    @State private var showDeleteScopeDialog = false
    

    @State private var pendingReps: Int = 1
    @State private var pendingPause: Int = 30
    @State private var pendingLoopDuration: Int = 120
    
    @State private var videoPlayerItem: VideoPlayerItem?
    



    @State private var editingScheduleId: UUID?  // ← Für EDIT!
    @State private var isEditingMode = false
    @State private var activeSheet: SheetType?
    @State private var selectedVideoForConfig: Video?
    @State private var playbackSettings = PlaybackSettings()
    
    @State private var showPlayAllSession = false

    enum SheetType: Identifiable {
        case
        library,
        profile,
        settings
        var id: Self { self }
    }

    // ✅ Computed property für sicheren Zugriff
       private var currentUser: User? {
           session.currentUser
       }
    
    
    var body: some View {
     
        ScrollView {
            VStack(spacing: 20) {
                
                // compactRingView
                DailyProgressCard()
                    .environmentObject(settingsVM)
                
                // Liste der heutigen Videos
                VStack(spacing: 4) { 
                ExercisesSection(
                    onToggleCompletion: { schedule in
                        progressVM.toggleCompletion(schedule, for: session.currentUser!)
                    },
                    onDelete: { schedule in
                        let rule = settingsVM.preferences
                            .getGoalFor(dayOfWeek: schedule.dayOfWeek)?.recurrenceRule ?? .single
                        
                        if rule == .single || !schedule.isAutoGenerated {
                            progressVM.removeSchedule(schedule, for: session.currentUser!)
                        } else {
                            pendingDeleteSchedule = schedule
                            showDeleteScopeDialog = true
                        }
                    },
                    onConfig: { schedule in
                        editingScheduleId = schedule.id
                        selectedVideoForConfig = schedule.video ?? Video.previewMobility
                        playbackSettings = PlaybackSettings(
                            repetitions: schedule.customRepetitions ?? 3,
                            pauseSeconds: schedule.customPauseSeconds ?? 30,
                            loopDurationSeconds: schedule.customLoopDurationSeconds
                                ?? schedule.video?.loopDurationSeconds
                                ?? 120
                        )
                    },
                    
                    
                    
                    onPlay: { schedule, video in
                        videoPlayerItem = VideoPlayerItem(
                            video: video,
                            scheduleId: schedule.id
                        )
                    },
                    onAddVideo: {
                        activeSheet = .library  // ← Sheet öffnet sich!
                    },
                    onRate: { schedule, rating in  // ← NEU
                           schedule.rating = rating
                           progressVM.updateSchedule(schedule, for: session.currentUser!)
                       },
                    onPlayAll: {                    // ← NEU
                        showPlayAllSession = true
                    }
                )
                
                
               
            }
        }
                .padding()
            }
        .background(Color(.systemGroupedBackground))
            .navigationTitle("Heute")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Menu {
                        Button("Profil") { activeSheet = .profile }
                            Button("Einstellungen") { activeSheet = .settings }
                    } label: {
                        // ✅ PROFILBILD STATT ICON
                                   if let user = session.currentUser,
                                      let imageData = user.profileImage,
                                      let uiImage = UIImage(data: imageData) {
                                       Image(uiImage: uiImage)
                                           .resizable()
                                           .scaledToFill()
                                           .frame(width: 35, height: 35)
                                           .clipShape(Circle())
                                   } else {
                                       Circle()
                                           .fill(Color.accentColor.opacity(0.3))
                                           .frame(width: 35, height: 35)
                                           .overlay(
                                               Text(session.currentUser?.initials ?? "?")
                                                   .font(.system(size: 14, weight: .bold))
                                                   .foregroundStyle(Color.accentColor)
                                           )
                                   }
                    }
                }
            }

            .sheet(item: $activeSheet) { sheet in
                switch sheet {
                case .settings:
                    SettingsView() // ← user Parameter
                        .environmentObject(settingsVM)   // ← VM injizieren!
                        .environment(\.modelContext, settingsVM.modelContext)
                        .onDisappear {
                            progressVM.loadToday(for: session.currentUser!)
                        }
                        
                case .profile:
                    ProfileView()
                        .environmentObject(session)
                        .environment(\.modelContext, profileVM.modelContext)
                case .library:
                    NavigationStack {
                        LibraryView(
                            // ✅ NEU
                            onVideoSelected: { video in
                                activeSheet = nil
                                
                                DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                                    pendingDate = Date()
                                    editingScheduleId = nil
                                    playbackSettings = PlaybackSettings(
                                        repetitions: video.defaultRepetitions,
                                        pauseSeconds: video.defaultPauseSeconds,
                                        loopDurationSeconds: video.loopDurationSeconds
                                    )
                                    selectedVideoForConfig = video  // ← öffnet Config-Sheet
                                }
                            }
                        )
                        .environmentObject(session)
                        .environmentObject(videoLibraryVM)
                        .environmentObject(settingsVM)
                    
                    }
        
                }
        }
        
            .sheet(item: $selectedVideoForConfig) { video in
                VideoQuickConfigSheet(
                    video: video,
                    initialRepetitions: playbackSettings.repetitions,
                    initialLoopDuration: playbackSettings.loopDurationSeconds,
                    initialPause: playbackSettings.pauseSeconds,
                    onAdd: { reps, loopDuration, pause in
                        if let scheduleId = editingScheduleId,
                           let schedule = progressVM.todaysSchedules.first(where: { $0.id == scheduleId }) {
                            // Bestehendes Schedule bearbeiten
                            schedule.customRepetitions = reps
                            schedule.customPauseSeconds = pause
                            schedule.customLoopDurationSeconds = loopDuration
                            progressVM.updateSchedule(schedule, for: session.currentUser!)
                            progressVM.loadToday(for: session.currentUser!)
                        } else {
                            // ✅ Neues Video hinzufügen
                            let rule = settingsVM.recurrenceRule(for: pendingDate)
                            print("🔍 HomeView onAdd: rule=\(rule.rawValue), pendingDate=\(pendingDate)")
                            if rule == .single {
                                progressVM.addVideo(
                                    video,
                                    to: pendingDate,
                                    for: session.currentUser!,
                                    customRepetitions: reps,
                                    customPauseSeconds: pause,
                                    customLoopDuration: loopDuration
                                )
                                progressVM.loadToday(for: session.currentUser!)
                            } else {
                                pendingVideo = video
                                pendingRecurrenceRule = rule
                                pendingReps = reps
                                   pendingPause = pause
                                   pendingLoopDuration = loopDuration
                                showScopeDialog = true
                            }
                        }
                        selectedVideoForConfig = nil
                        editingScheduleId = nil
                    
                    },
                    onCancel: {
                        selectedVideoForConfig = nil
                        editingScheduleId = nil
                    }
                )
            }
        // ⭐️ VIDEO PLAYER SHEET
        // ✅ Neu
        .sheet(item: $videoPlayerItem) { item in
            VideoPlayerView(
                video: item.video,
                scheduleId: item.scheduleId,
                progressViewModel: progressVM,
                session: session
            )
        }
        
        .sheet(isPresented: $showPlayAllSession) {
            PlayAllSessionView(
                schedules: progressVM.todaysSchedules,
                session: session,
                progressVM: progressVM
            )
            .environmentObject(progressVM)
        }

        
        // In HomeView nach dem letzten .sheet
        .confirmationDialog(
            "Video einplanen",
            isPresented: $showScopeDialog,
            titleVisibility: .visible
        ) {
            Button("Nur für diesen Tag") {
      
                if let video = pendingVideo {
                    print("🎯 Scope: onlyToday, date: \(pendingDate), video: \(video.title)")
                    settingsVM.addVideoWithScope(
                        video,
                        to: pendingDate,
                        for: session.currentUser!,
                        scope: .onlyToday,
                        progressVM: progressVM,
                        customRepetitions: pendingReps,      // ✅
                                   customPauseSeconds: pendingPause,    // ✅
                                   customLoopDuration: pendingLoopDuration // ✅
                    )
                }
                pendingVideo = nil
            }
            Button("Für alle \(pendingRecurrenceRule.rawValue) Termine") {
                if let video = pendingVideo {
                    settingsVM.addVideoWithScope(
                        video,
                        to: pendingDate,
                        for: session.currentUser!,
                        scope: .allFuture,
                        progressVM: progressVM,
                        customRepetitions: pendingReps,      // ✅
                                   customPauseSeconds: pendingPause,    // ✅
                                   customLoopDuration: pendingLoopDuration // ✅
                    )
                }
                pendingVideo = nil
            }
            Button("Abbrechen", role: .cancel) { pendingVideo = nil }
        } message: {
            Text("Soll \"\(pendingVideo?.title ?? "")\" nur heute oder für alle \(pendingRecurrenceRule.rawValue.lowercased()) Termine eingeplant werden?")
        }
        .confirmationDialog(
            "Video entfernen",
            isPresented: $showDeleteScopeDialog,
            titleVisibility: .visible
        ) {
            Button("Nur diesen Tag", role: .destructive) {
                if let schedule = pendingDeleteSchedule {
                    settingsVM.removeScheduleWithScope(
                        schedule,
                        for: session.currentUser!,
                        scope: .onlyToday,
                        progressVM: progressVM,
    
                    )
                }
                pendingDeleteSchedule = nil
            }
            Button("Alle zukünftigen Termine", role: .destructive) {
                if let schedule = pendingDeleteSchedule {
                    settingsVM.removeScheduleWithScope(
                        schedule,
                        for: session.currentUser!,
                        scope: .allFuture,
                        progressVM: progressVM,
                    )
                }
                pendingDeleteSchedule = nil
            }
            Button("Abbrechen", role: .cancel) { pendingDeleteSchedule = nil }
        } message: {
            Text("Soll \"\(pendingDeleteSchedule?.video?.title ?? "")\" nur heute oder für alle zukünftigen Termine entfernt werden?")
        }

            .onAppear {
                      guard let user = currentUser else {
                          print("⚠️ HomeView: Kein User eingeloggt")
                          return
                      }
                      progressVM.selectedDate = Date()
                      print("🏠 HomeView onAppear - currentUser.email: '\(user.email)'")
                      progressVM.loadHome(for: user)
                  }

            
    }
}

#Preview {
    let config = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(
        for: VideoSchedule.self, Video.self, User.self,
        configurations: config
    )
    let context = ModelContext(container)
    let sessionManager = SessionManager(
        userRepository: UserRepository(modelContext: context)
    )
    let progressVM = ProgressViewModel(modelContext: context, session: sessionManager)
    let settingsVM = SettingsViewModel(modelContext: context, session: sessionManager)
    let videoLibraryVM = VideoLibraryViewModel(
        repository: VideoRepository(
            modelContext: context,
            storageService: .shared,
            thumbnailService: .shared
        ),
        modelContext: context,
        session: sessionManager
    )
    let profileVM = ProfileViewModel(modelContext: context, session: sessionManager)

    NavigationStack {
        HomeView()
            .environmentObject(sessionManager)
            .environmentObject(progressVM)
            .environmentObject(videoLibraryVM)
            .environmentObject(settingsVM)
            .environmentObject(profileVM)
            .modelContainer(container)
    }
}
