
import SwiftUI
import SwiftData

struct HomeView: View {
    
    
    @EnvironmentObject var session: SessionManager

    @EnvironmentObject var progressVM: ProgressViewModel
    @EnvironmentObject var videoLibraryVM: VideoLibraryViewModel
    @EnvironmentObject var settingsVM: SettingsViewModel
    @EnvironmentObject var profileVM: ProfileViewModel
    @EnvironmentObject var appointmentViewModel: AppointmentViewModel
    
 
    @State private var pendingDate: Date = Date()
   
 
    @State private var pendingDeleteSchedule: VideoSchedule?
    @State private var showDeleteScopeDialog = false
    
    
    @State private var videoPlayerItem: VideoPlayerItem?
    



    @State private var editingScheduleId: UUID?  // ← Für EDIT!
    @State private var isEditingMode = false
    @State private var activeSheet: SheetType?
    @State private var selectedVideoForConfig: Video?
    @State private var playbackSettings = PlaybackSettings()
    
    @State private var showPlayAllSession = false
    
    @State private var selectedAppointment: Appointment? = nil

    enum SheetType: Identifiable {
        case
        videoPicker,
        profile,
        settings
        var id: Self { self }
    }

    // ✅ Computed property für sicheren Zugriff
       private var currentUser: User? {
           session.currentUser
       }
    
    
    var body: some View {
     
        ScrollView {
            VStack(spacing: 20) {
                
                // compactRingView
                DailyProgressCard()
                    .environmentObject(settingsVM)
                
                // Liste der heutigen Videos
                VStack(spacing: 4) { 
                ExercisesSection(
                    onToggleCompletion: { schedule in
                        progressVM.toggleCompletion(schedule, for: session.currentUser!)
                    },
                    onDelete: { schedule in
                        let rule = settingsVM.preferences
                            .getGoalFor(dayOfWeek: schedule.dayOfWeek)?.recurrenceRule ?? .single
                        
                        if rule == .single || !schedule.isAutoGenerated {
                            progressVM.removeSchedule(schedule, for: session.currentUser!)
                        } else {
                            pendingDeleteSchedule = schedule
                            showDeleteScopeDialog = true
                        }
                    },
                    onConfig: { schedule in
                        editingScheduleId = schedule.id
                        selectedVideoForConfig = schedule.video ?? Video.previewMobility
                        playbackSettings = PlaybackSettings(
                            repetitions: schedule.customRepetitions ?? 3,
                            pauseSeconds: schedule.customPauseSeconds ?? 30,
                            loopDurationSeconds: schedule.customLoopDurationSeconds
                                ?? schedule.video?.loopDurationSeconds
                                ?? 120
                        )
                    },
                    
                    
                    
                    onPlay: { schedule, video in
                        videoPlayerItem = VideoPlayerItem(
                            video: video,
                            scheduleId: schedule.id
                        )
                    },
                    onAddVideo: {
                        activeSheet = .videoPicker
                    },
                    onRate: { schedule, rating in  // ← NEU
                           schedule.rating = rating
                           progressVM.updateSchedule(schedule, for: session.currentUser!)
                       },
                    onPlayAll: {                    // ← NEU
                        showPlayAllSession = true
                    }
                )
                
                
               
            }
        }
                .padding()
            }
      
        
        .background(Color(.systemGroupedBackground))
            .navigationTitle("Heute")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Menu {
                        Button("Profil") { activeSheet = .profile }
                            Button("Einstellungen") { activeSheet = .settings }
                    } label: {
                        // ✅ PROFILBILD STATT ICON
                                   if let user = session.currentUser,
                                      let imageData = user.profileImage,
                                      let uiImage = UIImage(data: imageData) {
                                       Image(uiImage: uiImage)
                                           .resizable()
                                           .scaledToFill()
                                           .frame(width: 35, height: 35)
                                           .clipShape(Circle())
                                   } else {
                                       Circle()
                                           .fill(Color.accentColor.opacity(0.3))
                                           .frame(width: 35, height: 35)
                                           .overlay(
                                               Text(session.currentUser?.initials ?? "?")
                                                   .font(.system(size: 14, weight: .bold))
                                                   .foregroundStyle(Color.accentColor)
                                           )
                                   }
                    }
                }
            }
        

            .sheet(item: $activeSheet) { sheet in
                switch sheet {
                case .settings:
                    SettingsView()
                        .environmentObject(settingsVM)
                        .environmentObject(videoLibraryVM)  // ← NEU
                        .environmentObject(progressVM)       // ← NEU
                        .environment(\.modelContext, settingsVM.modelContext)
                        .onDisappear {
                            progressVM.loadToday(for: session.currentUser!)
                        }
                    
                case .profile:
                    ProfileView()
                        .environmentObject(session)
                        .environment(\.modelContext, profileVM.modelContext)
                case .videoPicker:
                    VideoPickerSheet { video in
                        activeSheet = nil
                        DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                            pendingDate = Date()
                            editingScheduleId = nil
                            playbackSettings = PlaybackSettings(
                                repetitions: video.defaultRepetitions,
                                pauseSeconds: video.defaultPauseSeconds,
                                loopDurationSeconds: video.loopDurationSeconds
                            )
                            selectedVideoForConfig = video
                        }
                    }
                    .environmentObject(videoLibraryVM)
                    .environmentObject(session)
                }
            }
            .sheet(item: $selectedVideoForConfig) { video in
                VideoQuickConfigSheet(
                    video: video,
                    activeMode: settingsVM.preferences.activeMode,  // ← NEU
                    initialRepetitions: playbackSettings.repetitions,
                    initialLoopDuration: playbackSettings.loopDurationSeconds,
                    initialPause: playbackSettings.pauseSeconds,
                    onAdd: { reps, loopDuration, pause, planMode in  // ← planMode NEU
                        if let scheduleId = editingScheduleId,
                           let schedule = progressVM.todaysSchedules.first(where: { $0.id == scheduleId }) {
                            schedule.customRepetitions = reps
                            schedule.customPauseSeconds = pause
                            schedule.customLoopDurationSeconds = loopDuration
                            progressVM.updateSchedule(schedule, for: session.currentUser!)
                            progressVM.loadToday(for: session.currentUser!)
                        } else {
                            progressVM.addVideo(
                                video,
                                to: pendingDate,
                                for: session.currentUser!,
                                planMode: planMode,  // ← NEU
                                customRepetitions: reps,
                                customPauseSeconds: pause,
                                customLoopDuration: loopDuration
                            )
                            progressVM.loadToday(for: session.currentUser!)
                        }
                        selectedVideoForConfig = nil
                        editingScheduleId = nil
                    },
                    onCancel: {
                        selectedVideoForConfig = nil
                        editingScheduleId = nil
                    }
                )
            }
        // ⭐️ VIDEO PLAYER SHEET
        // ✅ Neu
        .sheet(item: $videoPlayerItem) { item in
            VideoPlayerView(
                video: item.video,
                scheduleId: item.scheduleId,
                progressViewModel: progressVM,
                session: session
            )
        }
        
        .sheet(isPresented: $showPlayAllSession) {
            PlayAllSessionView(
                schedules: progressVM.todaysSchedules,
                session: session,
                progressVM: progressVM
            )
            .environmentObject(progressVM)
        }
        
        
        .sheet(item: $selectedAppointment) { appointment in
            AppointmentDetailView(appointment: appointment)
                .environmentObject(session)
                .environmentObject(appointmentViewModel)
        }
        
       
            .onAppear {
                      guard let user = currentUser else {
                          print("⚠️ HomeView: Kein User eingeloggt")
                          return
                      }
                      progressVM.selectedDate = Date()
                      print("🏠 HomeView onAppear - currentUser.email: '\(user.email)'")
                      progressVM.loadHome(for: user)
                  }

            
    }
    
}

#Preview {
    let config = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(
        for: VideoSchedule.self, Video.self, User.self,
        configurations: config
    )
    let context = ModelContext(container)
    let sessionManager = SessionManager(
        userRepository: UserRepository(modelContext: context)
    )
    

    let repository = VideoScheduleRepository(modelContext: context)
    let settingsVM = SettingsViewModel(
        modelContext: context,
        session: sessionManager,
        addScheduleUseCase: AddScheduleUseCase(repository: repository),
        removeScheduleUseCase: RemoveScheduleUseCase(repository: repository)
    )
    let progressVM = ProgressPreviewHelper.makeProgressVM(context: context)

    let videoLibraryVM = VideoLibraryViewModel(
        repository: VideoRepository(
            modelContext: context,
            storageService: .shared,
            thumbnailService: .shared
        ),
        modelContext: context,
        session: sessionManager
    )
    let profileVM = ProfileViewModel(
        userRepository: UserRepository(modelContext: context),
        session: sessionManager
    )

    NavigationStack {
        HomeView()
            .environmentObject(sessionManager)
            .environmentObject(progressVM)
            .environmentObject(videoLibraryVM)
            .environmentObject(settingsVM)
            .environmentObject(profileVM)
            .modelContainer(container)
    }
}
